Repository hzuapps/android-labs-2020, pull requests merged in 2020-12, with the labels that each got.

#1196 #5 #84 第五次实验
  students/net1814080903212/Accounting.java
  students/net1814080903212/DatabaseHelper.java
  students/net1814080903212/lab5.md
  students/net1814080903212/lab5result.png
Labels: Pass5

#1197 第4次实验报告
  students/net1814080903231/Lab/Lab_4.md
  students/net1814080903231/Lab/lab_4_1.jpg
  students/net1814080903231/Lab/lab_4_2.jpg
Labels: Pass4

#1198 实验报告5、6
  students/net1814080903226/Lab5-1.png
  students/net1814080903226/Lab5-2.png
  students/net1814080903226/Lab5.md
  students/net1814080903226/Lab6-1.png
  students/net1814080903226/Lab6.md
Labels: Good

#1201 #5 #66 第5次实验
  students/net1814080903106/src/main/java/edu/hzuapp/androidlabs/ScoreSave.java
Labels: Pass5

#1222 #6 #29 第6次实验
  students/net1814080903124/DonwloadSaveImg.java
  students/net1814080903124/FindImage.java
Labels: Good, Pass6

#1223 #65 实验5、实验报告5
  students/sec1814080911239/KnowledgeActivity.java
  students/sec1814080911239/Sec1814080911239MainActivity.java
  students/sec1814080911239/ShareActivity.java
  students/sec1814080911239/SolveActivity.java
  students/sec1814080911239/SplashActivity.java
  students/sec1814080911239/TextActivity.java
  students/sec1814080911239/activity_text.xml
  students/sec1814080911239/lab5.md
Labels: Pass5

#1272 实验1-4报告
  students/net1814080903321/1.1.jpg
  students/net1814080903321/1.jpg
  students/net1814080903321/2.jpg
  students/net1814080903321/3.jpg
  students/net1814080903321/4.1.jpg
  students/net1814080903321/4.jpg
  students/net1814080903321/lab1.md
  students/net1814080903321/lab2.md
  students/net1814080903321/lab3.md
  students/net1814080903321/lab4.md
Labels: Good

#1258 #5 #333 第五次实验+实验报告1、2、3、4
  students/sec1814080911219/app/src/main/AndroidManifest.xml
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/Sec1814080911219Activity.java
  students/sec1814080911219/app/src/main/res/layout/activity_main.xml
  students/sec1814080911219/lab1.PNG
  students/sec1814080911219/lab1.md
  students/sec1814080911219/lab2-1.PNG
  students/sec1814080911219/lab2-2.PNG
  students/sec1814080911219/lab2-3.PNG
  students/sec1814080911219/lab2.md
  students/sec1814080911219/lab3-1.PNG
  students/sec1814080911219/lab3-2 .PNG
  students/sec1814080911219/lab3-3.PNG
  students/sec1814080911219/lab3.md
  students/sec1814080911219/lab4-1.PNG
  students/sec1814080911219/lab4-2.PNG
  students/sec1814080911219/lab4-3.PNG
  students/sec1814080911219/lab4.md
Labels: Good, Pass5

#1229 #6 #22 第6次实验
  students/net1814080903230/GameActivity.java
  students/net1814080903230/MainActivity.java
  students/net1814080903230/SetActivity.java
  students/net1814080903230/activity_game.xml
Labels: Good, Pass6

#1230 #5 #70 第五次实验
  students/net1814080903219/AndroidManifest.xml
  students/net1814080903219/Course.java
  students/net1814080903219/Net1814080903219FileStoreActivity.java
  students/net1814080903219/PhysicalScore.java
  students/net1814080903219/PhysicalScoreActivity.java
  students/net1814080903219/QueryScoreActivity.java
  students/net1814080903219/activity_file_store.xml
  students/net1814080903219/lab5_result.png
  students/net1814080903219/lab6_result1.png
  students/net1814080903219/lab6_result2.png
  students/net1814080903219/lab6_result3.png
  students/net1814080903219/lab_5.md
  students/net1814080903219/lab_6.md
Labels: Pass5, Pass6

#1233 #5 #71 第5次实验
  students/net1814080903202/Comment1814080903202Activity.java
  students/net1814080903202/DatabaseHelper.java
Labels: Pass5

#1234 #6 第六次实验
  students/net1814080903120/FileDownloadActivity.java
  students/net1814080903120/FileDownloader.java
  students/net1814080903120/activity_file_download.xml
Labels: Pass6

#1235 第5次实验
  students/net1814080903138/Add1814080903138Activity.java
  students/net1814080903138/Check1814080903138Activity.java
  students/net1814080903138/Net1814080903138Activity.java
  students/net1814080903138/app/src/main/java/edu/hzuapps/androidlabs/net1814080903138/Add1814080903138Activity.java
  students/net1814080903138/app/src/main/java/edu/hzuapps/androidlabs/net1814080903138/Check1814080903138Activity.java
  students/net1814080903138/app/src/main/java/edu/hzuapps/androidlabs/net1814080903138/Net1814080903138Activity.java
  students/net1814080903138/app/src/main/res/drawable/et.xml
  students/net1814080903138/app/src/main/res/layout/activity_add1814080903138.xml
  students/net1814080903138/app/src/main/res/layout/activity_main.xml
Labels: Pass5

#1238 #5 #421 第5次实验
  students/net1814080903141/src/main/AndroidManifest.xml
  students/net1814080903141/src/main/java/edu/hzuapp/androidlabs/net1814080903141/ContentProviderOfRecords.java
  students/net1814080903141/src/main/java/edu/hzuapp/androidlabs/net1814080903141/GameActivity.java
  students/net1814080903141/src/main/java/edu/hzuapp/androidlabs/net1814080903141/Net1814080903141Activity.java
  students/net1814080903141/src/main/java/edu/hzuapp/androidlabs/net1814080903141/RecordActivity.java
  students/net1814080903141/src/main/res/layout/activity_game.xml
  students/net1814080903141/src/main/res/layout/activity_net1814080903141.xml
  students/net1814080903141/src/main/res/layout/activity_record.xml
Labels: Pass5

#1241 #6 #12 第6次实验
  students/net1814080903215/UpDownloadActivity.java
Labels: Pass6

#1243 #4 #266 第4次实验
  students/net1814080903314/activity_button.xml
  students/net1814080903314/activity_icon.xml
  students/net1814080903314/activity_main.xml
  students/net1814080903314/phot.png
  students/net1814080903314/sirr.png
Labels: Late, Pass4

#1245 #5 #165 第5次实验
  students/net1814080903137/实验五/CRUD.java
  students/net1814080903137/实验五/EditActivity.java
  students/net1814080903137/实验五/MainActivity.java
  students/net1814080903137/实验五/Note.java
  students/net1814080903137/实验五/NoteAdapter.java
  students/net1814080903137/实验五/NoteDatabase.java
  students/net1814080903137/实验六/AndroidManifest.xml
  students/net1814080903137/实验六/FileDownloadActivity.java
  students/net1814080903137/实验六/FileDownloader.java
  students/net1814080903137/实验六/HttpClientActivity.java
  students/net1814080903137/实验六/activity_http_client.xml
  students/net1814080903137/实验六/file_layout.xml
Labels: Pass5, Pass6

#1246 #5 #405 第五次实验
  students/sec1814080911138/ChartActivity.java
  students/sec1814080911138/CostBean.java
  students/sec1814080911138/DatabaseHelper.java
  students/sec1814080911138/Sec1814080911138Activity.java
Labels: Pass5

#1247 #13 实验五以及实验五报告
  students/net1814080903223/PlayActivity.java
  students/net1814080903223/ViewandmodifyActivity.java
  students/net1814080903223/activity_main.xml
  students/net1814080903223/activity_play.xml
  students/net1814080903223/activity_viewandmodify.xml
  students/net1814080903223/lab5.md
  students/net1814080903223/logo.jpg
  students/net1814080903223/shiyan501.png
  students/net1814080903223/shiyan502.png
Labels: Pass5

#1248 #5 #56 第五次实验
  students/net1814080903325/Net1814080903325Activity.java
Labels: Pass5

#1249 #5 #144 实验5
  students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/ReckonActivity.java
  students/net1814080903103/src/main/res/layout/activity_reckon.xml
Labels: Pass5

#1255 #5 #50 第5次实验（第二次提交）
  students/sec1814080911106/AddActivity.java
  students/sec1814080911106/Android 开发环境.png
  students/sec1814080911106/Sec1814080911106Activity.java
  students/sec1814080911106/activity_add.xml
  students/sec1814080911106/activity_main.xml
  students/sec1814080911106/实验1截图.png
  students/sec1814080911106/实验目录.png
Labels: Pass5

#1256 #5 #277 第5次实验
  students/sec1814080911111/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911111/Sec1814080911111Activity.java
  students/sec1814080911111/app/src/main/java/helper/FileHelper.java
  students/sec1814080911111/lab2.png
  students/sec1814080911111/lab3.png
  students/sec1814080911111/lab4.png
Labels: Pass5

#1269 #5 #122 第5次实验
  students/net1814080903116/src/main/Net1814080903116Activity.java
  students/net1814080903116/src/main/PostActivity.java
  students/net1814080903116/src/main/TreeholdActivity.java
  students/net1814080903116/src/main/activity_main.xml
  students/net1814080903116/src/main/activity_post.xml
  students/net1814080903116/src/main/activity_treehold.xml
Labels: Pass5

#1270 #4 #315 提交实验4
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/LookPyqActivity.java
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/Sec1814080911118Activity.java
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/SendPyqActivity.java
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/listview/Message.java
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/listview/MessageAdapter.java
  students/sec1814080911118/app/src/main/res/layout/activity_look_pyq.xml
  students/sec1814080911118/app/src/main/res/layout/activity_main.xml
  students/sec1814080911118/app/src/main/res/layout/activity_send_pyq.xml
  students/sec1814080911118/app/src/main/res/layout/message_item.xml
  students/sec1814080911118/app/src/main/res/values/colors.xml
  students/sec1814080911118/app/src/main/res/values/strings.xml
Labels: Pass4

#1280 #6 #158 第六次实验
  students/net1814080903113/HttpClientUIActivity.java
  students/net1814080903113/activity_http_client.xml
Labels: Pass6

#1281 实验六内容以及实验报告5,6
  students/net1814080903206/repor6.md
  students/net1814080903206/report5.md
  students/net1814080903206/six/ShoppingCar.java
  students/net1814080903206/six/shoping_car.xml
  students/net1814080903206/tesephoto/t5.jpg
  students/net1814080903206/tesephoto/t61.jpg
  students/net1814080903206/tesephoto/t62.jpg
Labels: Pass6

#1283 实验报告1-4
  students/sec1814080911106/lab1-1.png
  students/sec1814080911106/lab1-2.png
  students/sec1814080911106/lab1-3.png
  students/sec1814080911106/lab1.md
  students/sec1814080911106/lab2.md
  students/sec1814080911106/lab2.png
  students/sec1814080911106/lab3.md
  students/sec1814080911106/lab3.png
  students/sec1814080911106/lab4-1.png
  students/sec1814080911106/lab4-2.png
  students/sec1814080911106/lab4.md
Labels: Good

#1282 #6 #22 第六次实验报告
  students/net1814080903230/E6.png
  students/net1814080903230/lab6.md
Labels: Pass6

#1285 #5 #42 第五次实验
  students/sec1814080911210/FilesTextActivity.java
  students/sec1814080911210/activity_files_text.xml
Labels: Pass5

#1289 #5 #72 实验5
  students/net1814080903333/MainActivity.java
  students/net1814080903333/MyHelper.java
  students/net1814080903333/Net1814080903333StudentsInformationActivity2.java
  students/net1814080903333/Net814080903333TeacherHomeActivity.java
  students/net1814080903333/lab1.md
  students/net1814080903333/res/.DS_Store
  students/net1814080903333/res/layout/studentsinformationactivity2_net1814080903333.xml
  students/net1814080903333/res/layout/teacherhomehctivity_net1814080903333.xml
Labels: Pass5

#1301 #5 #255 第5次实验
  students/sec1814080911234/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911234/CreateActivity.java
  students/sec1814080911234/app/src/main/rec/layout/activity_create.xml
Labels: Pass5

#1306 #6 #86 第6次实验
  students/net1814080903239/FileDownActivity.java
  students/net1814080903239/FileDownloader.java
  students/net1814080903239/HttpClientActivity.java
  students/net1814080903239/activity_file_down.xml
  students/net1814080903239/activity_http_client.xml
  students/net1814080903239/sy5.1.png
  students/net1814080903239/sy5.2.png
Labels: Pass6

#1309 #6 #122 第六次实验
  students/net1814080903116/src/main/PostActivity.java
  students/net1814080903116/src/main/TreeholdActivity.java
  students/net1814080903116/src/main/activity_main.xml
  students/net1814080903116/src/main/activity_post.xml
  students/net1814080903116/src/main/activity_treehold.xml
  students/net1814080903116/src/main/button_main.xml
  students/net1814080903116/src/main/button_treehold.xml
Labels: Pass6

#1321 #5、6 #24 第五、六次实验报告和实验代码
  students/net1814080903111/Net1814080903111Activity.java
  students/net1814080903111/activity_record.java
  students/net1814080903111/lab5.md
  students/net1814080903111/lab5_1.png
  students/net1814080903111/lab5_2.png
  students/net1814080903111/lab5_3.png
  students/net1814080903111/lab6.md
  students/net1814080903111/lab6_1.png
  students/net1814080903111/lab6_2.png
Labels: Pass5, Pass6

#1333 #4 #499 第四次实验
  students/net1814080903313/activity_2.xml
  students/net1814080903313/activity_main.xml
  students/net1814080903313/img1.jpg
  students/net1814080903313/img2.png
  students/net1814080903313/img3.png
  students/net1814080903313/img4.png
  students/net1814080903313/img5.png
  students/net1814080903313/lab1.md
Labels: Pass4

#1345 #5 #375 第五次实验
  students/sec1814080911203/java/edu/hzuapps/androidlabs/sec1814080911203/FinancialActivity.java
  students/sec1814080911203/java/edu/hzuapps/androidlabs/sec1814080911203/InquireActivity.java
  students/sec1814080911203/java/edu/hzuapps/androidlabs/sec1814080911203/Sec1814080911203Activity.java
  students/sec1814080911203/java/edu/hzuapps/androidlabs/sec1814080911203/TransferActivity.java
Labels: Pass5

#1352 #6 #31 第6次实验
  students/net1814080903119/MyImageView.java
  students/net1814080903119/SaveImageUrl.java
  students/net1814080903119/StaticPageActivity.java
Labels: Pass6

#1353 #6 #59 实验6
  students/net1814080903303/ClassActivity.java
  students/net1814080903303/activity_class.xml
  students/net1814080903303/sixth_1.jpg
Labels: Pass6

#1355 #6 #78 第6次实验
  students/net1814080903221/Net1814080903221CountDownActivity.java
  students/net1814080903221/activity_net1814080903221_count_down.xml
Labels: Pass6

#1356 #6 #21 第6次实验
  students/net1814080903209/AccountActivity.java
  students/net1814080903209/JsonParse.java
  students/net1814080903209/User.java
  students/net1814080903209/activity_account.xml
  students/net1814080903209/user.json
Labels: Good, Pass6

#1357 #5 #81 第5次实验
  students/net1814080903220/Net1814080903220EditActivity.java
Labels: Pass5

#1359 #5 #63 第五次实验
  students/sec1814080911128/NewSaveAccount.java
  students/sec1814080911128/Sec1814080911128Activity.java
  students/sec1814080911128/activity_main.xml
  students/sec1814080911128/lab/lab5-1.png
  students/sec1814080911128/lab/lab5-2.png
Labels: Pass5

#1365 #5 #6
  students/net1814080903114/AddActivity.java
  students/net1814080903114/DatabaseHelper.java
  students/net1814080903114/activity_add.xml
Labels: Pass5, Pass6

#1366 #5 #251 第五次实验
  students/net1814080903338/DBOpenHelper.java
  students/net1814080903338/ReadActivity.java
  students/net1814080903338/User.java
  students/net1814080903338/UserDao.java
  students/net1814080903338/WriteActivity.java
  students/net1814080903338/activity_read.xml
  students/net1814080903338/activity_write.xml
Labels: Pass5

#1369 #5 #202 第5次实验
  students/sec1814080911222/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911222/PerformanceActivity.java
  students/sec1814080911222/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911222/PlanActivity.java
Labels: Pass5

#1370 #5 #38 第五次实验
  students/sec1814080911217/EarnIntegralActivity.java
  students/sec1814080911217/ExchangeIntegralActivity.java
  students/sec1814080911217/Record_Activity.java
  students/sec1814080911217/Sec1814080911217Activity.java
  students/sec1814080911217/activity_earn_integral.xml
  students/sec1814080911217/activity_exchange_integral.xml
  students/sec1814080911217/activity_main.xml
  students/sec1814080911217/activity_record.xml
  students/sec1814080911217/lab2.PNG
  students/sec1814080911217/shiyan1.jpg
  students/sec1814080911217/shiyan1.png
Labels: Pass5

#1371 #45 提交实验五代码和图片
  students/sec1814080911243/fine/AndroidManifest.xml
  students/sec1814080911243/fine/InforAdapter.java
  students/sec1814080911243/fine/Pet_circleActivity.java
  students/sec1814080911243/fine/pet_circle_activity.xml
  students/sec1814080911243/fine/reminders_activity.xml
  students/sec1814080911243/fine/微信图片_20201215201018.png
  students/sec1814080911243/fine/微信图片_20201215201019.png
  students/sec1814080911243/fine/微信图片_202012152010191.png
  students/sec1814080911243/fine/微信图片_202012152010192.png
Labels: Pass5

#1381 #5 #302 第五次实验
  students/sec1814080911214/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911214/DepositActivity.java
  students/sec1814080911214/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911214/QueryActivity.java
Labels: Pass5

#1407 #12 实验报告6
  students/net1814080903215/MainActivity.java
  students/net1814080903215/PersonalHomeActivity.java
  students/net1814080903215/activity_main.xml
  students/net1814080903215/activity_personal_home.xml
  students/net1814080903215/activity_up_download.xml
  students/net1814080903215/lab6.md
  students/net1814080903215/lab6_pic.jpg
Labels: Pass6

#1409 #6 #267 第6次实验
  students/net1814080903329/AndroidManifest.xml
  students/net1814080903329/HomeworkMangerActivity.java
  students/net1814080903329/HttpUrlConnectionActivity.java
  students/net1814080903329/MainActivity.java
  students/net1814080903329/PictureActivity.java
  students/net1814080903329/SaveImageViewActivity.java
  students/net1814080903329/activity_http_url_connection.xml
  students/net1814080903329/activity_main.xml
  students/net1814080903329/activity_save_image_view.xml
  students/net1814080903329/lab5.PNG
  students/net1814080903329/lab6.PNG
  students/net1814080903329/lab7.PNG
Labels: Pass6

#1410 #6 #251 第六次实验
  students/net1814080903338/Net1814080903338Activity.java
  students/net1814080903338/ReadActivity.java
  students/net1814080903338/ReviseActivity.java
  students/net1814080903338/UserDao.java
  students/net1814080903338/WriteActivity.java
  students/net1814080903338/activity_net1814080903338.xml
  students/net1814080903338/activity_revise.xml
  students/net1814080903338/activity_write.xml
Labels: Pass6

#1411 #65 #6 实验六、实验报告六
  students/sec1814080911239/ShareActivity.java
  students/sec1814080911239/activity_share.xml
  students/sec1814080911239/lab6.md
Labels: Pass6

#1429 #5 #37 第五次实验
  students/sec1814080911113/MusicPlayer/app/src/main/res/layout/next_activity.xml
  students/sec1814080911113/MusicPlayer/app/src/main/res/layout/pause_activity.xml
  students/sec1814080911113/text5/AndroidManifest.xml
  students/sec1814080911113/text5/LocalMusicAdapter.java
  students/sec1814080911113/text5/LocalMusicBean.java
  students/sec1814080911113/text5/Permission.java
  students/sec1814080911113/text5/Sec1814080911113Activity.java
  students/sec1814080911113/text5/activity_main.xml
  students/sec1814080911113/text5/mymusic_activity.xml
  students/sec1814080911113/text5/text5 picture.PNG
Labels: Pass5

#1431 #6 #34 第6次实验
  students/sec1814080911202/AndroidManifest.xml
  students/sec1814080911202/HttpClientActivity.java
  students/sec1814080911202/activity_http_client.xml
  students/sec1814080911202/lab6.md
  students/sec1814080911202/lab6.png
Labels: Pass6

#1437 实验报告5-7
  students/net1814080903116/src/main/5.1.PNG
  students/net1814080903116/src/main/5.2.PNG
  students/net1814080903116/src/main/6.1.PNG
  students/net1814080903116/src/main/6.2.PNG
  students/net1814080903116/src/main/7.1.PNG
  students/net1814080903116/src/main/实验报告5.md
  students/net1814080903116/src/main/实验报告6.md
  students/net1814080903116/src/main/实验报告7.md
Labels: Good

#1438 #6 #396 第六次实验
  students/net1814080903127/Net1814080903127Activity.java
  students/net1814080903127/iconmonstr_note.png
  students/net1814080903127/list.xml
Labels: Pass6

#1439 第六次实验
  students/net1814080903319/Net1814080903319MainActivity.java
  students/net1814080903319/activity_net1814080903319.xml
Labels: Pass6

#1440 #6 #50 实验六
  students/sec1814080911106/activity_http_picture.xml
  students/sec1814080911106/httpPictureActivity.java
  students/sec1814080911106/lab5.md
  students/sec1814080911106/lab5.png
  students/sec1814080911106/lab6.md
Labels: Pass5, Pass6

#1444 #6 #71 第6次实验
  students/net1814080903202/Moment1814080903202Activity.java
  students/net1814080903202/RoundTransform.java
Labels: Pass6

#1474 #3 #407 第3次实验
  students/net1814080903214/src/main/res/drawable/transparentwords.png
  students/net1814080903214/src/main/res/layout/MainActivity.xml
  students/net1814080903214/src/main/res/layout/ResetActivity.xml
  students/net1814080903214/src/main/res/layout/StartActivity.xml
Labels: Pass3

#1471 #5 #248 第5次实验
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/Net1814080903337Activity.java
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/RecordActivity.java
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/SeekActivity.java
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/SeekResult.java
Labels: Pass5

#1478 #7 #396 第七次实验+实验6、7报告
  students/net1814080903127/AndroidManifest.xml
  students/net1814080903127/Receiver.java
  students/net1814080903127/RemindActivity.java
  students/net1814080903127/RemindAdapter.java
  students/net1814080903127/RemindAdd.java
  students/net1814080903127/RemindDBHelper.java
  students/net1814080903127/ShowTip.java
  students/net1814080903127/activity_remind.xml
  students/net1814080903127/activity_remind_add.xml
  students/net1814080903127/iconmonstr_bell.png
  students/net1814080903127/lab6.md
  students/net1814080903127/lab6.png
  students/net1814080903127/lab7.1.png
  students/net1814080903127/lab7.2.png
  students/net1814080903127/lab7.md
  students/net1814080903127/list_remind.xml
Labels: Pass6, Pass7

#1480 #6 #52 第六次实验
  students/net1814080903304/activity_linear_list.xml
Labels: Pass6

#1488 #65 #7 实验7 实验报告7
  students/sec1814080911239/TakephotoActivity.java
  students/sec1814080911239/activity_takephoto.xml
  students/sec1814080911239/lab7.md
Labels: Pass7

#1492 #5 #272 第5次实验
  students/net1814080903340/ContentProviderActivity.java
  students/net1814080903340/ContentProviderOfBooks.java
  students/net1814080903340/activity_content_provider.xml
Labels: Pass5

#1494 #5 #319 #实验五 和 实验报告1-3
  students/sec1814080911131/1814080911131-杨竟楠-Android实验1#1.md
  students/sec1814080911131/1814080911131-杨竟楠-Android实验2#2.md
  students/sec1814080911131/1814080911131-杨竟楠-Android实验3#3.md
  students/sec1814080911131/AndroidManifest.xml
  students/sec1814080911131/Four_Activity.java
  students/sec1814080911131/FriendAdapter.java
  students/sec1814080911131/four_layout_activity.xml
  students/sec1814080911131/item_phone_book_friend.xml
  students/sec1814080911131/实验图片.png
  students/sec1814080911131/微信图片_20201214110452.png
  students/sec1814080911131/微信图片_202012141104521.png
  students/sec1814080911131/微信图片_202012141104522.png
Labels: Pass6

#1497 #6 #101 第六次实验
  students/net1814080903318/activity_net1814080903318.xml
Labels: Pass6
