Repository hzuapps/android-labs-2020, pull requests merged in 2020-09, with the labels that each got.

#87 #1 #28 第1次实验
  students/net1814080903213/Net1814080903213Activity.java
Labels: Good, Pass1

#90 #1 #71 第1次实验
  students/net1814080903202/Net1814080903202Activity.java
Labels: Good, Pass1

#91 #1 #67 第一次实验
  students/net1814080903226/Net1814080903226Activity.java
Labels: Good, Pass1

#93 #1 #84 第1次实验
  students/net1814080903212/Net1814080903212Activity.java
Labels: Good, Pass1

#95 #1 #11 第1次实验
  students/net1814080903211/Net1814080903211Activity.java
Labels: Good, Pass1

#97 #1 #48 第1次实验
  students/net1814080903216/Net1814080903216.java
Labels: Good, Pass1

#100 #1 #10 第1次实验
  students/net1806081301122/Net1806081301122Activity.java
Labels: Good, Pass1

#102 #1 #85 第一次实验
  students/net181408090323131/net1814080903231Activity.java
Labels: Good, Pass1

#103 #1 #81 第1次实验
  students/net1814080903220/net1814080903220.java
Labels: Good, Pass1

#104 #1 #69 第1次实验
  students/net1814080903108/Net1814080903108Activity.java
Labels: Good, Pass1

#105 #1 #21 第1次实验
  students/net1814080903209/Net1814080903209Activity.java
Labels: Good, Pass1

#106 #1 #70 第1次实验
  students/net1814080903219/Net1814080903219Activity.java
Labels: Good, Pass1

#109 提交实验一代码
  students/net1814080903304/Net1814080903304Activity.java
  students/net1814080903304/net1814080903304.jpg
Labels: Good, Pass1

#114 #1 #63 第一次实验
  students/sec1814080911128/Sec1814080911128.png
  students/sec1814080911128/Sec1814080911128Activity.java
Labels: Good, Pass1

#118 #1 #22 第1次实验
  students/net1814080903230/Net1814080903230Activity.java
Labels: Good, Pass1

#120 #1 #119 第1次实验
  students/net1814080903122/Net1814080903122Activity.java
Labels: Good, Pass1

#123 #1 #107 第1次实验
  students/net1814080903240/Net1814080903240Activity.java
Labels: Good, Pass1

#125 #1 #66 第一次实验
  students/net1814080903106/Net1814080903106Activity.java
Labels: Good, Pass1

#135 #1 #64 第一次实验
  students/net1814080903133/1.png
  students/net1814080903133/Net1814080903133Activity.java
Labels: Good, Pass1

#137 #1 提交实验一代码
  students/net1814080903102/Net1814080903102Activity.java
Labels: Good, Pass1

#138 #1 #134 第一次实验
  students/net1814080903129/Net1814080903129Activity.java
Labels: Good, Pass1

#139 #1 #129 第一次实验
  students/net1814080903101/Net1814080903101Activity.java
Labels: Good, Pass1

#147 #1 #122 第一次实验
  students/net1814080903116/Net1814080903116Activity.java
Labels: Good, Pass1

#149 #1 提交实验一代码
  students/net1814080903134/net1814080903134Activity.java
Labels: Good, Pass1

#150 #1 #131 第一次实验
  students/net1814080903132/Net1814080903132Activity.java
Labels: Good, Pass1

#151 #1 #145 第1次实验
  students/net1814080903126/Net1814080903126Activity.java
Labels: Good, Pass1

#199 #1 提交实验一代码
  students/sec1814080911108/Sec1814080911108Activity.java
  students/sec1814080911108/安装成功截图.png
Labels: Good, Pass1

#203 #1 #202 第1次实验
  students/sec1814080911222/edu/hzuapps/androidlabs/sec1814080911222/Sec1814080911222Activity.java
  students/sec1814080911222/sec1814080911222.png
Labels: Good, Pass1

#219 #1 #36 第一次实验
  students/sec1814080911129/Sec1814080911129Activity.java
Labels: Good

#285 #1 #282 第一次实验
  students/sec1814080911224/anroid.PNG
  students/sec1814080911224/edu/hzuapps/androidlabs/sec1814080911224/Sec1814080911224Activity.java
Labels: Good

#289 #1 #283 第1次实验
  students/sec1814080911213/edu/hzuapps/androidlabs/sec1814080911213/Sec1814080911213Activity.java
  students/sec1814080911213/sec1814080911213.png
Labels: Good

#291 #1 #284 第1次实验
  students/sec1814080911208/edu/hzuapps/androidlabs/sec1814080911208/Sec1814080911208Activity.java
  students/sec1814080911208/sec1814080911208.jpg
Labels: Good

#297 #1 #277 第1次实验
  students/sec1814080911111/1.png
  students/sec1814080911111/Sec1814080911111Activity.java
Labels: Good

#298 #1 #296 第1次实验
  students/sec1814080911236/edu/hzuapps/androidlabs/sec1814080911236/Sec1814080911236Activity.java
  students/sec1814080911236/微信图片_20200927231608.png
Labels: Good, Pass1

#301 #1 #300 第1次实验
  students/sec1814080911207/3ff808460bf951cbc5230a002b41e56.png
  students/sec1814080911207/edu/hzuapps/androidlabs/sec1814080911207/Sec1814080911207Activity.java
Labels: Good, Pass1

#303 #1 #302 第1次实验
  students/sec1814080911214/edu/hzuapps/androidlabs/sec1814080911214/Sec1814080911214Activity.java
  students/sec1814080911214/sec1814080911214.png
Labels: Good, Pass1

#316 #2 #67 第二次实验
  students/net1814080903226/AndroidManifest.xml
  students/net1814080903226/Net1814080903226MainviewActivity.java
  students/net1814080903226/Net1814080903226MessageViewActivity.java
  students/net1814080903226/Net1814080903226MyViewActivity.java
  students/net1814080903226/实验一.docx
Labels: Good, Pass2

#317 #1 #41 第一次实验
  students/sec1814080911205/Sec1814080911205Activity.java
Labels: Good

#337 #1 #139 第1次实验
  students/sec1814080911139/Sec1814080911139Activity.java
Labels: Good

#339 #1 #333 第一次实验
  students/sec1814080911219/Sec1814080911219Activity.java
  students/sec1814080911219/捕获.PNG
Labels: Good

#340 第一次实验
  students/net1814080903335/Net1814080903335Activity.java
  students/net1814080903335/net1814080903335Activity.png
Labels: Good

#341 第一次实验
  students/net1814080903334/Net1814080903334Activity.java
  students/net1814080903334/net1814080903334Activicity.png
Labels: Good

#349 #1 #305 第一次实验
  students/net1814080903308/Net1814080903308Activity.java
  students/net1814080903308/net1814080903308.png
Labels: Good

#355 #1 #47 第1次实验
  students/sec1814080911223/Sec1814080911223Activity.java
Labels: Good

#356 #1 #255 第1次实验
  students/sec1814080911234/Sec1814080911234Activity.java
Labels: Good
