Repository hzuapps/android-labs-2020, pull requests merged in 2020-11, with the labels that each got.

#813 第三次实验
  students/sec1814080911239/activity_main.xml
  students/sec1814080911239/drawable/ic_launcher_background.xml
  students/sec1814080911239/drawable/main_background.png
  students/sec1814080911239/drawable/splash_background.png
Labels: Pass3

#822 #2 #405 第二次实验
  students/sec1814080911138/AboutActivity.java
  students/sec1814080911138/AndroidManifest.xml
  students/sec1814080911138/ChartActivity.java
  students/sec1814080911138/Sec1814080911138Activity.java
Labels: Pass2

#823 #4 提交实验四代码
  students/net1814080903301/activity_book.xml
  students/net1814080903301/activity_select.xml
Labels: Pass4

#824 #3 #第三次实验
  students/sec1814080911131/baidudenglv.jpg
  students/sec1814080911131/splash_activity.xml
Labels: Pass3

#827 #3 #277 第3次实验
  students/sec1814080911111/app/src/main/res/drawable/image.jpg
  students/sec1814080911111/app/src/main/res/layout/activity_main.xml
Labels: Pass3

#828 #3 #47 第三次实验
  students/sec1814080911223/res/drawable/again.png
  students/sec1814080911223/res/drawable/begin.png
  students/sec1814080911223/res/drawable/beijing.png
  students/sec1814080911223/res/drawable/chuizi.png
  students/sec1814080911223/res/drawable/didong.png
  students/sec1814080911223/res/drawable/end.png
  students/sec1814080911223/res/drawable/ic_launcher_background.xml
  students/sec1814080911223/res/drawable/kai.jpg
  students/sec1814080911223/res/drawable/kuang.png
  students/sec1814080911223/res/drawable/laoshu.png
  students/sec1814080911223/res/layout/activity_fen.xml
  students/sec1814080911223/res/layout/activity_kai.xml
  students/sec1814080911223/res/layout/activity_main.xml
Labels: Pass3

#829 #4 #305 第4次实验
  students/net1814080903308/activity_music.xml
  students/net1814080903308/activity_net1814080903308.xml
  students/net1814080903308/activity_share.xml
  students/net1814080903308/logo3.jpg
  students/net1814080903308/p1.png
  students/net1814080903308/p3.jpg
Labels: Pass4

#830 #4 #13 第四次实验
  students/net1814080903223/activity_main.xml
  students/net1814080903223/activity_play.xml
  students/net1814080903223/activity_viewandmodify.xml
Labels: Pass4

#831 #4 提交实验四代码
  students/net1814080903113/Net1814080903113MainActivity.java
  students/net1814080903113/Net1814080903113PhotoShowActivity.java
  students/net1814080903113/aqua1.png
  students/net1814080903113/net1814080903113photoshow.xml
Labels: Pass4

#834 #4 #29 第四次实验
  students/net1814080903124/AndroidManifest.xml
  students/net1814080903124/Net1814080903124ACCActivity.java
  students/net1814080903124/Net1814080903124ClothesActivity.java
  students/net1814080903124/Net1814080903124MainActivity.java
  students/net1814080903124/Net1814080903124SneakerActivity.java
  students/net1814080903124/acc_01.jpg
  students/net1814080903124/acc_02.jpg
  students/net1814080903124/acc_03.jpg
  students/net1814080903124/activity_net1814080903124_acc.xml
  students/net1814080903124/activity_net1814080903124_clothes.xml
  students/net1814080903124/activity_net1814080903124_main.xml
  students/net1814080903124/activity_net1814080903124_sneaker.xml
  students/net1814080903124/background.jpg
  students/net1814080903124/background2.jpg
  students/net1814080903124/background3.jpg
  students/net1814080903124/clothes_01.jpg
  students/net1814080903124/clothes_02.jpg
  students/net1814080903124/clothes_03.jpg
  students/net1814080903124/main_background.png
  students/net1814080903124/shoes_01.jpg
  students/net1814080903124/shoes_02.jpg
  students/net1814080903124/shoes_03.jpg
  students/net1814080903124/shoes_04.jpg
  students/net1814080903124/shoes_05.jpg
  students/net1814080903124/shoes_06.jpg
  students/net1814080903124/shoes_07.jpg
  students/net1814080903124/shoes_08.jpg
  students/net1814080903124/shoes_09.jpg
Labels: Pass4

#837 #3 #405 第三次实验
  students/sec1814080911138/activity_sec1814080911138.xml
  students/sec1814080911138/yz1.jpg
Labels: Pass3

#835 #3 #323 第三次实验
  students/sec1814080911125/activity_fail_game_scene.xml
  students/sec1814080911125/activity_success_game.xml
  students/sec1814080911125/failscene.png
  students/sec1814080911125/successscene.png
Labels: Pass3

#843 #4 #281 第4次实验
  students/net1814080903321/ShowActivity.java
  students/net1814080903321/StoreActivity.java
  students/net1814080903321/activity_net1814080903321.xml
  students/net1814080903321/activity_show.xml
  students/net1814080903321/activity_store.xml
  students/net1814080903321/hualaishi.jpg
  students/net1814080903321/jiroujuan.jpg
  students/net1814080903321/jituibao.jpg
  students/net1814080903321/kaonai.jpg
  students/net1814080903321/maidanglao.jpg
  students/net1814080903321/zhujiaofan.jpg
Labels: Pass4

#844 #4 #56 第四次实验
  students/net1814080903325/AndroidManifest.xml
  students/net1814080903325/Net1814080903325Activity1.java
  students/net1814080903325/PlayerActivity.java
  students/net1814080903325/activity_net1814080903325.xml
  students/net1814080903325/activity_player.xml
Labels: Pass4

#845 #4 #59 第四次实验
  students/net1814080903303/activity_class.xml
  students/net1814080903303/activity_infomation.xml
  students/net1814080903303/activity_net1814080903303.xml
  students/net1814080903303/activity_student.xml
  students/net1814080903303/classing_backgroud.jpg
  students/net1814080903303/home_backgroud.png
  students/net1814080903303/information_collect_backgroud.jpg
  students/net1814080903303/leave_information_backgroud.jpg
Labels: Pass4

#842 #4 #49 第四次实验
  students/net1814080903118/Net1814080903118LendAckActivity.java
  students/net1814080903118/Net1814080903118PayAckActivity.java
  students/net1814080903118/Net1814080903118PersonalActivity.java
  students/net1814080903118/Net1814080903118WorkLendActivity.java
  students/net1814080903118/Net1814080903118WorkUnLendActivity.java
  students/net1814080903118/README.md
  students/net1814080903118/activity_net_1814080903118_lend_ack.xml
  students/net1814080903118/activity_net_1814080903118_pay_ack.xml
  students/net1814080903118/activity_net_1814080903118_personal.xml
  students/net1814080903118/activity_net_1814080903118_work_lend.xml
  students/net1814080903118/效果图.jpg
Labels: Pass4

#849 #4 #101 第4次实验
  students/net1814080903318/activity_luping.xml
  students/net1814080903318/activity_my_video.xml
  students/net1814080903318/activity_net1814080903318.xml
  students/net1814080903318/lp.png
  students/net1814080903318/video1.jpg
Labels: Pass4

#851 #3 #283 第3次实验
  students/sec1814080911213/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911213/PerformanceActivity.java
  students/sec1814080911213/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911213/RankActivity.java
  students/sec1814080911213/app/src/main/res/drawable/bg.jpg
  students/sec1814080911213/app/src/main/res/drawable/performance.jpg
  students/sec1814080911213/app/src/main/res/drawable/rank.jpg
  students/sec1814080911213/app/src/main/res/layout/activity_performance.xml
  students/sec1814080911213/app/src/main/res/layout/activity_rank.xml
  students/sec1814080911213/app/src/main/res/layout/sec_1814080911213_activity.xml
Labels: Pass3

#852 “#3 #282 第3次实验"
  students/sec1814080911224/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911224/DrawActivity.java
  students/sec1814080911224/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911224/ShuffleActivity.java
  students/sec1814080911224/app/src/main/res/drawable/background.jpg
  students/sec1814080911224/app/src/main/res/drawable/drawable.jpg
  students/sec1814080911224/app/src/main/res/drawable/shuffle.jpg
  students/sec1814080911224/app/src/main/res/layout/activity_draw.xml
  students/sec1814080911224/app/src/main/res/layout/activity_shuffle.xml
  students/sec1814080911224/app/src/main/res/layout/sec_1814080911224_activity.xml
Labels: Pass3

#854 #4 #78 第4次实验
  students/net1814080903221/activity_main.xml
  students/net1814080903221/activity_net1814080903221_count_down.xml
  students/net1814080903221/activity_net1814080903221_watch_stop.xml
Labels: Pass4

#859 #4 #84 第四次实验
  students/net1814080903212/Activity_accounting.xml
  students/net1814080903212/Activity_list_view_item.xml
  students/net1814080903212/activity_accountbook.xml
  students/net1814080903212/lab1.md
  students/net1814080903212/lab1result.PNG
  students/net1814080903212/lab2.md
  students/net1814080903212/lab2result1.PNG
  students/net1814080903212/lab2result2.PNG
  students/net1814080903212/lab2result3.PNG
  students/net1814080903212/lab3.md
  students/net1814080903212/lab3result.PNG
  students/net1814080903212/lab4.md
  students/net1814080903212/lab4result1.PNG
  students/net1814080903212/lab4result2.PNG
Labels: Good, Pass4

#865 #4 #267 第4次实验
  students/net1814080903329/AndroidManifest.xml
  students/net1814080903329/Net1814080903329Activity.java
  students/net1814080903329/activity_homework_manger.xml
  students/net1814080903329/activity_main.xml
  students/net1814080903329/activity_net1814080903329.xml
  students/net1814080903329/secondActivity.java
  students/net1814080903329/strings.xml
Labels: Pass4

#866 #3 #300 第3次实验
  students/sec1814080911207/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911207/RecordActivity.java
  students/sec1814080911207/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911207/RemindActivity.java
  students/sec1814080911207/app/src/main/res/drawable/bg.jpg
  students/sec1814080911207/app/src/main/res/drawable/record.jpg
  students/sec1814080911207/app/src/main/res/drawable/remind.jpg
  students/sec1814080911207/app/src/main/res/layout/activity_record.xml
  students/sec1814080911207/app/src/main/res/layout/activity_remind.xml
  students/sec1814080911207/app/src/main/res/layout/sec_1814080911207_activity.xml
Labels: Pass3

#867 #4 #363 第4次实验
  students/net1814080903237/app/src/main/java/edu/hzuapps/androidlabs/net1814080903237/MainActivity.java
  students/net1814080903237/app/src/main/java/edu/hzuapps/androidlabs/net1814080903237/ManageActivity.java
  students/net1814080903237/app/src/main/res/drawable/shouy.png
  students/net1814080903237/app/src/main/res/layout/activity_main.xml
  students/net1814080903237/app/src/main/res/layout/activity_manage.xml
  students/net1814080903237/app/src/main/res/layout/activity_sell.xml
Labels: Good, Pass4

#871 #4 #10 第4次实验
  students/net1806081301122/activity_help.xml
  students/net1806081301122/activity_main.xml
  students/net1806081301122/activity_setting.xml
Labels: Good, Pass4

#874 #4 #396 第四次实验
  students/net1814080903127/activity_add.xml
  students/net1814080903127/activity_remind.xml
Labels: Good, Pass4

#876 #4 #131 第四次实验
  students/net1814080903132/activity_ask.xml
  students/net1814080903132/activity_comment.xml
  students/net1814080903132/second_1.jpg
  students/net1814080903132/second_2.jpg
Labels: Good, Pass4

#878 #4 #382 第四次实验
  students/net1814080903130/activity_main.xml
  students/net1814080903130/content_main.xml
Labels: Good, Pass4

#881 #4 #142 第四次实验
  students/net1814080903117/app/src/main/res/layout/activity_download.xml
  students/net1814080903117/app/src/main/res/layout/activity_net1814080903117.xml
  students/net1814080903117/app/src/main/res/layout/activity_upload.xml
Labels: Pass4

#882 #4 #171 第四次实验
  students/net1814080903104/AndroidManifest.xml
  students/net1814080903104/GetReward.java
  students/net1814080903104/Net1814080903104Activity.java
  students/net1814080903104/SearchMess.java
  students/net1814080903104/res/layout/activity_get_reward.xml
  students/net1814080903104/res/layout/activity_main.xml
  students/net1814080903104/res/layout/activity_search_mess.xml
Labels: Pass4

#894 #4 #69 实验4
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/presenter/CreatePresenter.java
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/presenter/HomePresenter.java
  students/net1814080903108/src/main/res/drawable/title.png
  students/net1814080903108/src/main/res/layout/activity_net1814080903108.xml
  students/net1814080903108/src/main/res/layout/fragment_create.xml
  students/net1814080903108/src/main/res/layout/fragment_home.xml
  students/net1814080903108/src/main/res/layout/item_scene.xml
  students/net1814080903108/主界面-无内容.png
  students/net1814080903108/主界面-有内容.png
  students/net1814080903108/新建界面-起名.png
  students/net1814080903108/新建界面-选择前.png
  students/net1814080903108/新建界面-选择后.png
Labels: Pass4

#906 #4 #30 第四次实验
  students/net1814080903105/ListActivity.java
  students/net1814080903105/activity_list.xml
  students/net1814080903105/activity_main.xml
  students/net1814080903105/activity_shopping.xml
  students/net1814080903105/activity_splist_view_item.xml
  students/net1814080903105/h01.jpg
  students/net1814080903105/h02.jpg
  students/net1814080903105/h03.jpg
  students/net1814080903105/h04.jpg
Labels: Pass4

#907 #4 #134 第4次实验
  students/net1814080903129/src/main/res/drawable/js.png
  students/net1814080903129/src/main/res/layout/activity_main.xml
  students/net1814080903129/src/main/res/layout/activity_operation.xml
  students/net1814080903129/src/main/res/layout/activity_shift.xml
Labels: Pass4

#908 #4 #163 第四次实验
  students/net1814080903131/src/main/res/layout/activity_main.xml
  students/net1814080903131/src/main/res/layout/activity_search.xml
  students/net1814080903131/src/main/res/layout/activity_translate.xml
Labels: Pass4

#909 #4 #421 第4次实验
  students/net1814080903141/src/main/res/drawable-v24/ic_launcher_foreground.xml
  students/net1814080903141/src/main/res/drawable-v24/logo.jpg
  students/net1814080903141/src/main/res/layout/activity_game.xml
  students/net1814080903141/src/main/res/layout/activity_net1814080903141.xml
  students/net1814080903141/src/main/res/layout/activity_record.xml
Labels: Pass4

#914 #4 #18 第四次实验
  students/net1814080903204/Lab1.md
  students/net1814080903204/Lab1.png
  students/net1814080903204/Lab2.md
  students/net1814080903204/Lab2.png
  students/net1814080903204/Lab3.png
  students/net1814080903204/Lab4-1.png
  students/net1814080903204/Lab4-2.png
  students/net1814080903204/activity_main.xml
  students/net1814080903204/logo.png
  students/net1814080903204/medicine.png
  students/net1814080903204/remind.xml
  students/net1814080903204/setting.xml
Labels: Pass4

#920 #4 #165 第四次实验
  students/net1814080903137/res/layout/activity_main.xml
  students/net1814080903137/res/layout/activity_remind.xml
  students/net1814080903137/res/layout/activity_set.xml
Labels: Pass4

#919 #4 #122 第四次实验
  students/net1814080903116/src/main/activity_treehold.xml
Labels: Pass4

#917 #4 #119 实验4
  students/net1814080903122/src/main/java/edu/hzuapps/androidlabs/presenter/SchedulesAdapter.java
  students/net1814080903122/src/main/res/layout/activity_main.xml
  students/net1814080903122/src/main/res/layout/fragment_schedules.xml
  students/net1814080903122/src/main/res/layout/fragment_timer.xml
  students/net1814080903122/src/main/res/layout/fragment_vedio.xml
  students/net1814080903122/src/main/res/layout/iteam_schedules.xml
  students/net1814080903122/计划表界面_效果截图.png
  students/net1814080903122/运动方式_效果截图.png
Labels: Pass4

#915 #4 #168 第四次实验
  students/net1814080903114/activity_add.xml
  students/net1814080903114/activity_delete.xml
Labels: Pass4

#911 #4 #202 第4次实验
  students/sec1814080911222/app/src/main/res/layout/activity_performance.xml
  students/sec1814080911222/app/src/main/res/layout/activity_plan.xml
  students/sec1814080911222/app/src/main/res/layout/sec_1814080911222_activity.xml
Labels: Pass4

#921 #4 #511 第四次实验
  students/net1814080903128/res/layout/activity_personal.xml
Labels: Pass4

#922 #3 #296 #第三次实验
  students/sec1814080911236/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911236/CheckpointActivity.java
  students/sec1814080911236/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911236/PropsActivity.java
  students/sec1814080911236/app/src/main/res/drawable/bg.jpg
  students/sec1814080911236/app/src/main/res/drawable/checkpoint.jpg
  students/sec1814080911236/app/src/main/res/drawable/props.jpg
  students/sec1814080911236/app/src/main/res/layout/activity_checkpoint.xml
  students/sec1814080911236/app/src/main/res/layout/activity_props.xml
  students/sec1814080911236/app/src/main/res/layout/sec_1814080911236_activity.xml
Labels: Pass3

#923 #4 #140第四次实验
  students/net1814080903134/app/src/res/layout/activity_main.xml
  students/net1814080903134/app/src/res/layout/activity_personal_center.xml
  students/net1814080903134/app/src/res/layout/activity_release_idle.xml
Labels: Pass4

#924 实验四实验报告
  students/net1814080903220/lab4result.jpg
  students/net1814080903220/lab_4.md
Labels: Pass4

#925 #4 #245 第四次实验
  students/net1814080903335/activity_main.xml
  students/net1814080903335/activity_read.xml
  students/net1814080903335/p.jpg
  students/net1814080903335/p1.jpg
  students/net1814080903335/p2.jpg
Labels: Pass4

#929 #4 #28 提交1-4实验报告
  students/net1814080903213/lab1.md
  students/net1814080903213/lab2.md
  students/net1814080903213/lab3.md
  students/net1814080903213/lab4.md
Labels: Good

#930 #3 #530 第三次实验
  students/sec1814080911139/activity_sec1814080911139_acitivity.xml
  students/sec1814080911139/bg1.png
Labels: Pass3

#934 #4 #63 第四次实验
  students/sec1814080911128/activity_main.xml
  students/sec1814080911128/bg.png
  students/sec1814080911128/imageview.xml
  students/sec1814080911128/news_item.xml
Labels: Pass4

#947 #4 #70 第四次实验
  students/net1814080903219/Net1814080903219Activity.java
  students/net1814080903219/PhysicalScoreActivity.java
  students/net1814080903219/QueryScoreActivity.java
  students/net1814080903219/activity_main.xml
  students/net1814080903219/activity_physical_score.xml
  students/net1814080903219/activity_query_score.xml
  students/net1814080903219/fanhui.jpg
  students/net1814080903219/lab1_result.png
  students/net1814080903219/lab2_result1.png
  students/net1814080903219/lab2_result2.png
  students/net1814080903219/lab3_result.png
  students/net1814080903219/lab4_result1.png
  students/net1814080903219/lab4_result2.png
  students/net1814080903219/lab4_result3.png
  students/net1814080903219/lab4_result4.png
  students/net1814080903219/lab_1.md
  students/net1814080903219/lab_2.md
  students/net1814080903219/lab_3.md
  students/net1814080903219/lab_4.md
  students/net1814080903219/score.png
Labels: Pass4

#955 #4 #133 第4次实验
  students/net1814080903135/activity_buyingtickets1814080903135.xml
  students/net1814080903135/activity_main.xml
  students/net1814080903135/activity_queryinterface1814080903135.xml
Labels: Pass4

#954 #4 #24 第四次实验
  students/net1814080903111/AndroidManifest.xml
  students/net1814080903111/Check_recordActivity.java
  students/net1814080903111/Net1814080903111Activity.java
  students/net1814080903111/activity_check_record.java
  students/net1814080903111/activity_check_record.xml
  students/net1814080903111/lab1.png
  students/net1814080903111/lab2_1.png
  students/net1814080903111/lab2_2.png
  students/net1814080903111/lab3.png
  students/net1814080903111/net_1814080903111_activity.xml
Labels: Pass4

#943 #4 #141 实验四
  students/net1814080903112/src/main/java/edu/hzuapps/androidlabs/RankActivity.java
  students/net1814080903112/src/main/res/layout/activity_game.xml
  students/net1814080903112/src/main/res/layout/activity_title.xml
Labels: Pass4

#945 #4 #405 第四次实验
  students/sec1814080911138/activity_about.xml
  students/sec1814080911138/activity_chart.xml
  students/sec1814080911138/activity_sec1814080911138.xml
Labels: Pass4

#973 #445 实验报告1234
  students/net1814080903123/report/1.png
  students/net1814080903123/report/2.png
  students/net1814080903123/report/3.1.png
  students/net1814080903123/report/3.2.png
  students/net1814080903123/report/4.1.png
  students/net1814080903123/report/4.2.png
  students/net1814080903123/report/Lab1.md
  students/net1814080903123/report/Lab2.md
  students/net1814080903123/report/Lab3.md
  students/net1814080903123/report/Lab4.md
Labels: Good

#1017 #4 #86 第4次实验
  students/net1814080903239/activity_net1814080903239.xml
  students/net1814080903239/activity_renthouse.xml
  students/net1814080903239/activity_showhouse.xml
  students/net1814080903239/sy1.png
Labels: Pass4

#1018 #4 #82 第4次实验
  students/net1814080903224/activity_main.xml
  students/net1814080903224/activity_recommend.xml
  students/net1814080903224/lab1.md
  students/net1814080903224/lab2.md
  students/net1814080903224/lab3.md
  students/net1814080903224/lab4.md
Labels: Pass4

#1065 #4 #255 第4次实验
  students/sec1814080911234/app/src/main/rec/drawable/date.jpg
  students/sec1814080911234/app/src/main/rec/drawable/fes.jpg
  students/sec1814080911234/app/src/main/rec/layout/activity_create.xml
  students/sec1814080911234/app/src/main/rec/layout/activity_date.xml
  students/sec1814080911234/app/src/main/rec/layout/activity_festival.xml
  students/sec1814080911234/app/src/main/rec/layout/activity_sec1814080911234.xml
Labels: Pass4

#1074 #4 #283 第4次实验
  students/sec1814080911213/app/src/main/res/layout/activity_performance.xml
  students/sec1814080911213/app/src/main/res/layout/activity_rank.xml
  students/sec1814080911213/app/src/main/res/layout/sec_1814080911213_activity.xml
Labels: Pass4

#1075 #4 #302 第四次实验
  students/sec1814080911214/app/src/main/res/layout/activity_deposit.xml
  students/sec1814080911214/app/src/main/res/layout/activity_query.xml
  students/sec1814080911214/app/src/main/res/layout/sec_1814080911214_activity.xml
Labels: Pass4

#1077 #4 #277 第4次实验
  students/sec1814080911111/app/src/main/res/layout/activity_countdown.xml
  students/sec1814080911111/app/src/main/res/layout/activity_main.xml
  students/sec1814080911111/app/src/main/res/layout/activity_timer.xml
  students/sec1814080911111/lab1.md
  students/sec1814080911111/lab1.png
  students/sec1814080911111/lab2.md
  students/sec1814080911111/lab2.png
  students/sec1814080911111/lab3.md
  students/sec1814080911111/lab3.png
  students/sec1814080911111/lab4.md
  students/sec1814080911111/lab4.png
Labels: Pass4

#1080 #5 #192 第五次实验
  students/net1814080903317/DBOpenHelper.java
  students/net1814080903317/FoundItMainAdapter.java
  students/net1814080903317/Info.java
  students/net1814080903317/InfoDao.java
  students/net1814080903317/Net1814080903317FoundItMainActivity.java
  students/net1814080903317/实验五运行结果.jpg
Labels: Pass5

#1081 #4 #375 第四次实验
  students/sec1814080911203/res/layout/activity_financial.xml
  students/sec1814080911203/res/layout/activity_inquire.xml
  students/sec1814080911203/res/layout/activity_main.xml
  students/sec1814080911203/res/layout/activity_transfer.xml
Labels: Pass4

#1082 #4 #38 第四次实验
  students/sec1814080911217/activity_earn_integral.xml
  students/sec1814080911217/activity_exchange_integral.xml
  students/sec1814080911217/activity_main.xml
  students/sec1814080911217/yingxionglianmeng.png
  students/sec1814080911217/zhuye.jpg
Labels: Pass4

#1083 #4 #61 第4次实验
  students/net1814080903315/activity_net1814080903315.xml
  students/net1814080903315/activity_save.xml
  students/net1814080903315/activity_seek.xml
  students/net1814080903315/activity_sorted.xml
Labels: Pass4

#1091 #4 #384 第4次实验
  students/sec1814080911142/Sec1814080911142Activity.java
  students/sec1814080911142/activity_main.xml
  students/sec1814080911142/app/src/main/AndroidManifest.xml
  students/sec1814080911142/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911142/Payment.java
  students/sec1814080911142/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911142/Register.java
  students/sec1814080911142/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911142/sec1814080911142Activity.java
  students/sec1814080911142/fkcg.xml
  students/sec1814080911142/imag2.jpg
  students/sec1814080911142/myimage.png
  students/sec1814080911142/smdl.xml
  students/sec1814080911142/运行截图.PNG
Labels: Pass4

#1108 #5 #78 第5次实验
  students/net1814080903221/Net1814080903221WatchStopActivity.java
  students/net1814080903221/activity_net1814080903221_watch_stop.xml
Labels: Pass5

#1101 第五次实验
  students/net1814080903210/lab5.md
  students/net1814080903210/lab5_res.png
Labels: Pass5

#1102 #5 #143 第5次实验
  students/net1814080903125/AddDiaryActivity.java
  students/net1814080903125/DatabaseHelper.java
Labels: Good, Pass5

#1103 #5 #142 第五次实验
  students/net1814080903117/app/src/main/AndroidManifest.xml
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/UploadActivity.java
Labels: Pass5

#1120 #5 #22 第5次实验
  students/net1814080903230/GameActivity.java
  students/net1814080903230/SetActivity.java
  students/net1814080903230/activity_game.xml
Labels: Pass5

#1121 #5 #23 第五次实验
  students/net1814080903102/app/src/main/java/edu/hzuapps/androidlabs/AddClassActivity.java
  students/net1814080903102/app/src/main/java/edu/hzuapps/androidlabs/ClassArray.java
  students/net1814080903102/app/src/main/java/edu/hzuapps/androidlabs/Course.java
  students/net1814080903102/app/src/main/java/edu/hzuapps/androidlabs/JsonIO.java
  students/net1814080903102/app/src/main/java/edu/hzuapps/androidlabs/Net1814080903102Activity.java
  students/net1814080903102/app/src/main/res/layout/activity_addclass.xml
Labels: Pass5

#1122 #5 #62 第5次实验
  students/net1814080903320/sqlite/DBOpenHelper.java
  students/net1814080903320/sqlite/RunDao.java
Labels: Pass5

#1125 第六次实验
  students/net1814080903210/Net1814080903210Activity.java
  students/net1814080903210/titles
Labels: Pass6

#1128 #5 #445 实验五
  students/net1814080903123/5.1.jpg
  students/net1814080903123/5.2.jpg
  students/net1814080903123/NovelSearch.java
Labels: Pass5

#1142 #6 #16 第6次实验
  students/net1814080903225/HttpClientActivity.java
  students/net1814080903225/activity_http_client.xml
Labels: Pass6

#1158 #4 #300 第4次实验
  students/sec1814080911207/app/src/main/res/layout/activity_record.xml
  students/sec1814080911207/app/src/main/res/layout/activity_remind.xml
  students/sec1814080911207/app/src/main/res/layout/sec_1814080911207_activity.xml
Labels: Pass4

#1157 #5 #22 实验报告五
  students/net1814080903230/E5.png
  students/net1814080903230/lab5.md
Labels: Pass5

#1156 #5 第五次实验
  students/net1814080903120/BorrowActivity.java
  students/net1814080903120/Borrowother.java
  students/net1814080903120/borrow.xml
Labels: Pass5

#1161 #6 #142 第六次实验
  students/net1814080903117/app/src/main/AndroidManifest.xml
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/DownloadActivity.java
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/UploadActivity.java
Labels: Pass6

#1173 #5 #34 第5次实验
  students/.DS_Store
  students/sec1814080911202/DatabaseHelper.java
  students/sec1814080911202/Sec1814080911202Activity.java
  students/sec1814080911202/ic_launcher_background.xml
  students/sec1814080911202/lab4.md
  students/sec1814080911202/lab4.png
  students/sec1814080911202/lab5.md
  students/sec1814080911202/lab5.png
  students/sec1814080911202/实验3运行截图.png
Labels: Pass5

#1174 #5 #64 第五次实验
  students/net1814080903133/SQLite效果截图.png
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/Net1814080903133Activity.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myActivity/NovelReadActivity.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myContreller/Book.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myContreller/BookManager.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myContreller/DatabaseHelper.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myContreller/MyListViewAdapter.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myContreller/MyTools.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myContreller/ReadViewpagerAdapter.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myContreller/readViewpagerAdapter.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myView/Info.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myView/ReadFragment.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/myView/readFragment.java
  students/net1814080903133/src/main/res/drawable/back_image1.jpg
  students/net1814080903133/src/main/res/layout/activity_net1814080903133.xml
  students/net1814080903133/src/main/res/layout/activity_novel_read.xml
  students/net1814080903133/src/main/res/layout/add_book_item.xml
  students/net1814080903133/src/main/res/layout/read_item_fragment.xml
  students/net1814080903133/src/main/res/layout/read_titlebar.xml
Labels: Pass5

#1177 #4 #296 第4次实验
  students/sec1814080911236/app/src/main/res/layout/activity_checkpoint.xml
  students/sec1814080911236/app/src/main/res/layout/activity_props.xml
  students/sec1814080911236/app/src/main/res/layout/sec_1814080911236_activity.xml
Labels: Pass4

#1186 #5 #41 第五次实验
  students/sec1814080911205/FileStorageActivity.java
  students/sec1814080911205/activity_add_text.xml
Labels: Pass5
