Repository hzuapps/android-labs-2020, pull requests merged in 2020-10, with the labels that each got.

#372 实验二：Android组件编程
  students/net1814080903118/MainActivity.java
  students/net1814080903118/Net1814080903118Activity.java
  students/net1814080903118/Net1814080903118LendAckActivity.java
  students/net1814080903118/Net1814080903118PayAckActivity.java
  students/net1814080903118/Net1814080903118PersonalActivity.java
  students/net1814080903118/Net1814080903118WorkLendActivity.java
  students/net1814080903118/Net1814080903118WorkUnLendActivity.java
  students/net1814080903118/activity_main.xml
  students/net1814080903118/搭建开发环境(Android Studio).jpg
Labels: Good, Pass2

#383 第一次实验
  students/sec1814080911230/Sec1814080911230Activity.java
Labels: Pass1

#391 #2 #192 第二次实验
  students/net1814080903317/AndroidManifest.xml
  students/net1814080903317/Net1814080903317Activity.java
  students/net1814080903317/Net1814080903317FoundItAddActivity.java
  students/net1814080903317/Net1814080903317FoundItMainActivity.java
  students/net1814080903317/Net1814080903317FoundItMyActivity.java
  students/net1814080903317/activity_foundit_main.xml
  students/net1814080903317/strings.xml
  students/net1814080903317/目录结构.jpg
Labels: Good, Pass2

#403 #2 #16 第2次实验
  students/net1814080903325/AndroidManifest.xml
  students/net1814080903325/Main1814080903225Activity2.java
  students/net1814080903325/Net1814080903325Activity.java
Labels: Good, Pass2

#413 #2 #81 第二次实验
  students/net1814080903220/AndroidManifest.xml
  students/net1814080903220/Net1814080903220EditActivity.java
  students/net1814080903220/Net1814080903220MainActivity.java
  students/net1814080903220/Net1814080903220PictureActivity.java
Labels: Good, Pass2

#414 #2 #63 第二次实验
  students/sec1814080911128/AndroidManifest.xml
  students/sec1814080911128/JsonParseActivity.java
  students/sec1814080911128/NewsInfoActivity.java
  students/sec1814080911128/Sec1814080911128Activity.java
Labels: Good, Pass2

#415 #2 #12 第2次实验
  students/net1814080903215/AndroidManifest.xml
  students/net1814080903215/MainActivity.java
  students/net1814080903215/PersonalHomeActivity.java
  students/net1814080903215/UpDownloadActivity.java
Labels: Good, Pass2

#416 #2第2次实验
  students/net1814080903316/AndroidManifest.xml
  students/net1814080903316/InformationActivity.java
  students/net1814080903316/Net1814080903316Activity.java
  students/net1814080903316/ToolActivity.java
  students/net1814080903316/net1814080903316.PNG
Labels: Good, Pass2

#422 #2 #15 第2次实验
  students/net1814080903207/AndroidManifest.xml
  students/net1814080903207/Net1814080903207Activity.java
  students/net1814080903207/Net1814080903207ReciteActivity.java
  students/net1814080903207/Net1814080903207WrongActivity.java
Labels: Good, Pass2

#423 #2 #22 第2次实验
  students/net1814080903230/AndroidManifest.xml
  students/net1814080903230/Net1814080903230MainActivity.java
  students/net1814080903230/Net1814080903230SetActivity.java
Labels: Good, Pass2

#428 #2 #69 第2次实验
  students/net1814080903108/src/main/AndroidManifest.xml
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/view/CreateFragment.java
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/view/HomeFragment.java
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/view/ListFragment.java
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/view/MainActivity.java
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/view/Net1814080903108Activity.java
Labels: Good, Pass2

#429 #2 #64 第2次实验
  students/net1814080903133/AndroidManifest.xml
  students/net1814080903133/BookActivity.java
  students/net1814080903133/Net1814080903133Activity.java
  students/net1814080903133/ReadActivity.java
Labels: Good, Pass2

#430 #2 #119 第二次实验
  students/net1814080903122/src/main/AndroidManifest.xml
  students/net1814080903122/src/main/java/edu/hzuapps/androidlabs/view/MainActivity.java
  students/net1814080903122/src/main/java/edu/hzuapps/androidlabs/view/Net1814080903122Activity.java
  students/net1814080903122/src/main/java/edu/hzuapps/androidlabs/view/SchedulesFragment.java
  students/net1814080903122/src/main/java/edu/hzuapps/androidlabs/view/TimerFragment.java
  students/net1814080903122/src/main/java/edu/hzuapps/androidlabs/view/VedioFragment.java
Labels: Good, Pass2

#441 #2 #143 第2次实验
  students/net1814080903125/AddDiaryActivity.java
  students/net1814080903125/Net1814080903125Activity.java
  students/net1814080903125/PasswordActivity.java
  students/net1814080903125/activity_main.xml
Labels: Good, Pass2

#442 #2 #142 第二次实验
  students/net1814080903117/app/src/main/AndroidManifest.xml
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/DownloadActivity.java
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/Net1814080903117Activity.java
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/UploadActivity.java
Labels: Good, Pass2

#446 #2 #18 第二次实验
  students/net1814080903204/AndroidManifest.xml
  students/net1814080903204/Copy1Activity.java
  students/net1814080903204/Copy2Activity.java
  students/net1814080903204/Net1814080903204Activity.java
Labels: Good, Pass2

#447 #2 #26 第二次实验
  students/net1814080903110/Activity1.java
  students/net1814080903110/Activity2.java
  students/net1814080903110/AndroidManifest.xml
  students/net1814080903110/Net1814080903110Activity.java
Labels: Pass2

#451 #2 #144 第2次实验
  students/net1814080903103/src/main/AndroidManifest.xml
  students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/ClockActivity.java
  students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/Net1814080903103Activity.java
  students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/ReckonActivity.java
Labels: Good, Pass2

#455 #2 #148 #第二个实验
  students/net1814080903136/AndroidManifest.xml
  students/net1814080903136/Compound1814080903136Activity.java
  students/net1814080903136/Edit1814080903136Activity.java
  students/net1814080903136/Net1814080903136Activity.java
Labels: Good, Pass2

#458 #2#171 第二次实验
  students/net1814080903104/GetReward.java
  students/net1814080903104/Net1814080903104Activity.java
  students/net1814080903104/SearchMess.java
  students/net1814080903104/activity_main.xml
Labels: Good, Pass2

#459 #2 #30 第二次实验
  students/net1814080903105/AndroidManifest.xml
  students/net1814080903105/ListActivity.java
  students/net1814080903105/Net1814080903105Activity.java
  students/net1814080903105/ShoppingActivity.java
Labels: Good, Pass2

#460 #2 #11 第二次实验
  students/net1814080903211/AndroidManifest.xml
  students/net1814080903211/BrowseActivity.java
  students/net1814080903211/Net1814080903211Activity.java
  students/net1814080903211/ProfileActivity.java
Labels: Good, Pass2

#462 #1 #13 第二次实验
  students/net1814080903223/AndroidManifest.xml
  students/net1814080903223/Net1814080903223Activity.java
  students/net1814080903223/PlayActivity.java
  students/net1814080903223/ViewandmodifyActivity.java
Labels: Good, Pass2

#463 #2 #140 第二次实验
  students/net1814080903134/app/src/main/AndroidManifest.xml
  students/net1814080903134/app/src/main/java/edu/hzuapp/androidlabs/net1814080903134/Net1814080903134Activity.java
  students/net1814080903134/app/src/main/java/edu/hzuapp/androidlabs/net1814080903134/PersonalCenterActivity.java
  students/net1814080903134/app/src/main/java/edu/hzuapp/androidlabs/net1814080903134/ReleaseIdleActivity.java
Labels: Good, Pass2

#471 #2 #154 第2次实验
  students/net1814080903115/src/main/AndroidManifest.xml
  students/net1814080903115/src/main/java/edu/hzuapps/androidlabs/net1814080903115/BrowseActivity.java
  students/net1814080903115/src/main/java/edu/hzuapps/androidlabs/net1814080903115/Net1814080903115Activity.java
  students/net1814080903115/src/main/java/edu/hzuapps/androidlabs/net1814080903115/PlayActivity.java
Labels: Pass2

#473 #2 #163 实验二
  students/net1814080903131/Net1814080903131Activity.java
  students/net1814080903131/src/main/AndroidManifest.xml
  students/net1814080903131/src/main/java/edu/hzuapps/androidlabs/net1814080903131/Net1814080903131Activity.java
  students/net1814080903131/src/main/java/edu/hzuapps/androidlabs/net1814080903131/SearchActivity.java
  students/net1814080903131/src/main/java/edu/hzuapps/androidlabs/net1814080903131/TranslateActivity.java
Labels: Pass2

#474 #2 #445 第二次实验
  students/net1814080903123/AndroidManifest.xml
  students/net1814080903123/MyBookshelf.java
  students/net1814080903123/Net1814080903123Activity.java
  students/net1814080903123/NovelSearch.java
Labels: Pass2

#475 #2 提交实验二代码
  students/net1814080903124/AndroidManifest.xml
  students/net1814080903124/Net1814080903124Activity.java
  students/net1814080903124/Net1814080903124ContentActivity.java
  students/net1814080903124/Net1814080903124GameActivity.java
Labels: Good, Pass2

#480 #2 #156 第二次实验
  students/net1814080903138/Add1814080903138Activity.java
  students/net1814080903138/AndroidManifest.xml
  students/net1814080903138/Check1814080903138Activity.java
  students/net1814080903138/Net1814080903138Activity.java
Labels: Pass2

#491 #2 #286 第二次实验
  students/net1814080903322/AndroidManifest.xml
  students/net1814080903322/Funtion_Next.java
  students/net1814080903322/Net1814080903322Activity.java
  students/net1814080903322/Net1814080903326Activity.java
  students/net1814080903322/net1814080903322.PNG
Labels: Pass2

#495 #2 #435 第二次实验
  students/net1814080903302/AndroidManifest.xml
  students/net1814080903302/Net1814080903302Activity.java
  students/net1814080903302/RecordingLine.java
  students/net1814080903302/StartRecording.java
Labels: Pass2

#529 #2 #28 第2次实验
  students/net1814080903213/AndroidManifest.xml
  students/net1814080903213/Net1814080903213Activity.java
  students/net1814080903213/SubmitResultActivity.java
  students/net1814080903213/WordListActivity.java
Labels: Pass2

#517 #2 #70 第二次实验
  students/net1814080903219/AndroidManifest.xml
  students/net1814080903219/Net1814080903219Activity.java
  students/net1814080903219/PhysicalScoreActivity.java
  students/net1814080903219/QueryScoreActivity.java
  students/net1814080903219/activity_main.xml
  students/net1814080903219/logo.jpg
Labels: Good, Pass2, Pass3

#518 #3 #67 第三次实验
  students/net1814080903226/hzu_logo.png
  students/net1814080903226/net_1814080903226_myview_activity.xml
Labels: Good, Pass3

#519 #3 #16 第3次实验
  students/net1814080903225/Net1814080903225_Clock.xml
  students/net1814080903225/res/drawable/clock.jpg
  students/net1814080903325/Net1814080903225Activity.java
Labels: Good, Pass3

#520 #3#10第3次实验
  students/net1806081301122/activity_main.xml
  students/net1806081301122/res/drawable/logo.jpg
Labels: Good, Pass3

#521 #3 #19 第3次实验
  students/net1814080903210/activity_info.xml
  students/net1814080903210/logo.jpg
Labels: Good, Pass3

#523 #3 #81 第3次实验
  students/net1814080903220/activity_show.xml
  students/net1814080903220/white.png
Labels: Good, Pass3

#524 #3 #71 第3次实验
  students/net1814080903202/activity_net1814080903202.xml
  students/net1814080903202/logo.png
Labels: Good, Pass3

#525 #3 #18 第三次实验
  students/net1814080903204/activity_main.xml
  students/net1814080903204/logo.jpg
Labels: Good, Pass3

#526 #3 #48 第3次实验
  students/net1814080903216/activity_main.xml
  students/net1814080903216/bg.png
Labels: Good, Pass3

#537 #2 #280 第二次实验
  students/net1814080903326/AndroidManifest.xml
  students/net1814080903326/Net1814080903326Activity.java
  students/net1814080903326/PageTurning1.java
Labels: Pass2

#538 #2 #101 第2次实验
  students/net1814080903318/main/AndroidManifest.xml
  students/net1814080903318/main/java/edu/hzuapps/androidlabs/LupingActivity.java
  students/net1814080903318/main/java/edu/hzuapps/androidlabs/MyVideoActivity.java
  students/net1814080903318/main/java/edu/hzuapps/androidlabs/Net1814080903318Activity.java
Labels: Pass2

#539 #2 #245 第二次实验
  students/net1814080903335/AndroidManifest.xml
  students/net1814080903335/Net1814080903335Activity.java
  students/net1814080903335/ReadActivity.java
  students/net1814080903335/net1814080903335Activity.png
Labels: Pass2

#540 #2 #80 第二次实验
  students/net1814080903234/AndroidManifest.xml
  students/net1814080903234/ContactActivity.java
  students/net1814080903234/DynamicActivity.java
  students/net1814080903234/Net1814080903234Activity.java
Labels: Pass2

#544 #2 提交实验二代码
  students/net1814080903301/AndroidManifest.xml
  students/net1814080903301/BookActivity.java
  students/net1814080903301/Net1814080903301Activity.java
  students/net1814080903301/SelectActivity.java
Labels: Pass2

#545 #2 #315 第二次实验
  students/net1814080903315/AndroidManifest.xml
  students/net1814080903315/Net1814080903315MainActivity.java
  students/net1814080903315/SaveActivity.java
  students/net1814080903315/SeekActivity.java
  students/net1814080903315/SortedActivity.java
Labels: Pass2

#546 #2 #59 第二次实验
  students/net1814080903303/AndroidManifest.xml
  students/net1814080903303/ClassActivity.java
  students/net1814080903303/InformationActivity.java
  students/net1814080903303/Net1814080903303Activity.java
  students/net1814080903303/StudentActivity.java
  students/net1814080903303/activity_class.xml
  students/net1814080903303/activity_infomation.xml
  students/net1814080903303/activity_net1814080903303.xml
  students/net1814080903303/activity_student.xml
  students/net1814080903303/android_picture.png
Labels: Pass2

#549 #2 #263 提交实验二代码
  students/README.md
  students/net1814080903328/AndroidManifest.xml
  students/net1814080903328/Net1814080903328Activity.java
  students/net1814080903328/RuleActivity.java
  students/net1814080903328/activity_rule.xml
  students/net1814080903328/beida.png
  students/net1814080903328/net1814080903328.PNG
Labels: Pass2

#550 #2 #266 第二次实验
  students/net1814080903314/AndroidManifest.xml
  students/net1814080903314/ButtonActivity.java
  students/net1814080903314/Net1814080903314Activity.java
Labels: Pass2

#553 #2 #72 第二次实验
  students/Net1814080903333/Net1814080903333Activity.java
  students/Net1814080903333/Net1814080903333Picture.png
  students/net1814080903333/AndroidManifest.xml
  students/net1814080903333/MainActivity.java
  students/net1814080903333/Net1814080903333StudentsInformationActivity2.java
  students/net1814080903333/Net814080903333TeacherHomeActivity.java
Labels: Pass2

#559 #2 #122 第二次实验
  students/net1814080903116/Net1814080903116Activity.java
  students/net1814080903116/src/main/AndroidManifest.xml
  students/net1814080903116/src/main/Net1814080903116Activity.java
  students/net1814080903116/src/main/PostActivity.java
  students/net1814080903116/src/main/TreeholdActivity.java
Labels: Pass2

#560 #2 #396 第二次实验
  students/net1814080903127/AddActivity.java
  students/net1814080903127/AndroidManifest.xml
  students/net1814080903127/Net1814080903127Activity.java
  students/net1814080903127/RemindActivity.java
Labels: Pass2

#551 #3 #192 第三次实验
  students/net1814080903317/activity_foundit_main.xml
  students/net1814080903317/my.png
Labels: Good, Pass3

#561 #3 #78 第3次实验
  students/net1814080903221/activity_main.xml
  students/net1814080903221/image.jpg
Labels: Good, Pass3

#566 #2 #85 第2次实验
  students/net1814080903231/AndroidManifest.xml
  students/net1814080903231/java/edu/hzuapps/android/net1814080903231/ChatInterfaceActivity.java
  students/net1814080903231/java/edu/hzuapps/android/net1814080903231/ContactPersonActivity.java
  students/net1814080903231/java/edu/hzuapps/android/net1814080903231/MainActivity.java
  students/net1814080903231/net1814080903231Activity.java
Labels: Pass2

#571 #1 #567 第1次实验
  students/net1814080903201/Net1814080903201Activity.java
Labels: Late, Pass1

#563 #3 #12 第3次实验
  students/net1814080903215/activity_main.xml
  students/net1814080903215/bg.png
Labels: Good, Pass3

#564 #3 #22 第3次实验
  students/net1814080903230/activity_main.xml
  students/net1814080903230/logo.jpg
Labels: Good, Pass3

#569 #3 #84 第三次实验
  students/net1814080903212/Activity_net1814080903212.xml
  students/net1814080903212/main_table.jpg
Labels: Good, Pass3

#572 #3 #21 第3次实验
  students/net1814080903209/AndroidManifest.xml
  students/net1814080903209/CountActivity.java
  students/net1814080903209/Net1814080903209Activity.java
  students/net1814080903209/ShowActivity.java
  students/net1814080903209/activity_main.xml
  students/net1814080903209/bc.jpg
Labels: Good, Pass3

#574 #3 #60 第三次实验
  students/net1814080903319/activity_net1814080903319.xml
  students/net1814080903319/theone.jpg
Labels: Good, Pass3

#562 #3 #63 第三次实验
  students/sec1814080911128/activity_main.xml
  students/sec1814080911128/newslogo.jpg
Labels: Good, Pass3

#577 #2 #244 第2次实验
  students/net1814080903203/AndroidManifest.xml
  students/net1814080903203/ManageActivity.java
  students/net1814080903203/Net1814080903203Activity.java
  students/net1814080903203/ViewActivity.java
  students/net1814080903203/net_1814080903203_activity.xml
  students/net1814080903203/strings.xml
Labels: Pass2

#582 #1 #126 第1次实验
  students/net1814080903229/Net1814080903229Activity.java
  students/net1814080903229/Net1814080903229MainActivity.java
  students/net1814080903229/Net1814080903229TravelActivity.java
Labels: Pass2

#583 #2 #27 第二次实验
  students/net1814080903107/AndroidManifest.xml
  students/net1814080903107/Buy.java
  students/net1814080903107/Command.java
  students/net1814080903107/Net1814080903107Acivity.java
  students/net1814080903107/Recommend.java
  students/net1814080903107/Search.java
Labels: Pass2

#584 #1 #407 第一次实验
  students/net1814080903214/Net1814080903214Activity.java
  students/net1814080903214/app/src/main/AndroidManifest.xml
  students/net1814080903214/app/src/main/java/edu/hzuapps/androidlabs/Net1814080903214Activity.java
  students/net1814080903214/app/src/main/java/edu/hzuapps/androidlabs/ResetActivity.java
  students/net1814080903214/app/src/main/java/edu/hzuapps/androidlabs/StartActivity.java
Labels: Pass2

#585 #2 #329 第二次实验
  students/sec1814080911130/app/src/main/AndroidManifest.xml
  students/sec1814080911130/app/src/main/java/edu/hzuapps/androidlabs/OptionsActivity.java
  students/sec1814080911130/app/src/main/java/edu/hzuapps/androidlabs/PlayActivity.java
  students/sec1814080911130/app/src/main/java/edu/hzuapps/androidlabs/Sec1814080911130Activity.java
Labels: Good, Pass2

#586 第二次实验
  students/net1814080903218/AndroidManifest.xml
  students/net1814080903218/AskForLeave1814080903218Activity.java
  students/net1814080903218/Net1814080903218Activity.java
Labels: Pass2

#590 #2 #20 第二次实验
  students/net1814080903140/AndroidManifest.xml
  students/net1814080903140/CityManageActivity.java
  students/net1814080903140/CityMangeActivity.java
  students/net1814080903140/Net1814080903140Activity.java
  students/net1814080903140/SearchCityActivity.java
Labels: Pass2

#593 #2 #168 第二次实验
  students/net1814080903114/AddActivity.java
  students/net1814080903114/AndroidManifest.xml
  students/net1814080903114/DeleteActivity.java
  students/net1814080903114/Net1814080903114Activity.java
Labels: Pass2

#596 #2 #131 第二次实验
  students/net1814080903132/AndroidManifest.xml
  students/net1814080903132/AskActivity.java
  students/net1814080903132/CommentActivity.java
  students/net1814080903132/Net1814080903132Activity.java
Labels: Pass2

#598 #2 #145 实验2
  students/net1814080903126/src/main/AndroidManifest.xml
  students/net1814080903126/src/main/java/edu/hzuapps/androidlabs/ContinueGameActivity.java
  students/net1814080903126/src/main/java/edu/hzuapps/androidlabs/GameActivity.java
  students/net1814080903126/src/main/java/edu/hzuapps/androidlabs/Net1814080903126Activity.java
  students/net1814080903126/src/main/java/edu/hzuapps/androidlabs/ScoreActivity.java
Labels: Pass2

#599 #2 #141 实验2
  students/net1814080903112/src/main/AndroidManifest.xml
  students/net1814080903112/src/main/java/edu/hzuapps/androidlabs/GameActivity.java
  students/net1814080903112/src/main/java/edu/hzuapps/androidlabs/Net1814080903112Activity.java
  students/net1814080903112/src/main/java/edu/hzuapps/androidlabs/RankActivity.java
Labels: Pass2

#576 #3 #14 第3次实验
  students/net1814080903205/activity_main.xml
  students/net1814080903205/tu3.jpg
Labels: Good, Pass3

#578 #3 #28 第3次实验
  students/net1814080903213/Net1814080903213Activity.java
  students/net1814080903213/activity_main.xml
  students/net1814080903213/ic_search.xml
Labels: Good, Pass3

#579 #3 #80 第三次实验
  students/net1814080903234/activity_net1814080903234.xml
  students/net1814080903234/buttonbg.png
Labels: Good, Pass3

#587 #3 #13 第三次实验
  students/net1814080903223/AndroidManifest.xml
  students/net1814080903223/Net1814080903223Activity.java
  students/net1814080903223/PlayActivity.java
  students/net1814080903223/ViewandmodifyActivity.java
  students/net1814080903223/activity_main.xml
  students/net1814080903223/logo.jpg
Labels: Good, Pass3

#601 #3 #69 实验3
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/view/MainActivity.java
  students/net1814080903108/src/main/java/edu/hzuapps/androidlabs/view/Net1814080903108Activity.java
  students/net1814080903108/src/main/java/edu/hzuapps/res/drawable/title.png
  students/net1814080903108/src/main/java/edu/hzuapps/res/layout/activity_net1814080903108.xml
Labels: Good, Pass3

#617 #2 #248 第二次实验
  students/net1814080903337/Net1814080903337/app/src/main/AndroidManifest.xml
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/MainActivity.java
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/Net1814080903337Activity.java
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/OverdueActivity.java
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/RecordActivity.java
  students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/SeekActivity.java
Labels: Pass2

#629 #1 #143 第三次实验
  students/net1814080903125/AndroidManifest.xml
  students/net1814080903125/PasswordActivity.java
  students/net1814080903125/activity_main.xml
  students/net1814080903125/res/drawable/diary.jpg
  students/net1814080903125/res/drawable/lock.jpg
  students/net1814080903125/res/layout/activity_add_diary.xml
  students/net1814080903125/res/layout/activity_main.xml
  students/net1814080903125/res/layout/activity_password.xml
Labels: Pass3

#632 #2 #251 第二次实验
  students/net1814080903338/AndroidManifest.xml
  students/net1814080903338/Net1814080903338Activity.java
  students/net1814080903338/ReadActivity.java
  students/net1814080903338/WriteActivity.java
Labels: Pass2

#602 #3 #119 实验3
  students/net1814080903122/src/main/res/drawable/fit.png
  students/net1814080903122/src/main/res/layout/activity_net1814080903122.xml
Labels: Good, Pass3

#603 #3 #148 第三次实验
  students/net1814080903136/src/main/res/drawable/music.jpg
  students/net1814080903136/src/main/res/layout/activity_main.xml
Labels: Good, Pass3

#604 #3 #156 第三次实验
  students/net1814080903138/app/src/main/res/drawable/homework.jpg
  students/net1814080903138/app/src/main/res/layout/activity_main.xml
Labels: Good, Pass3

#615 #3 #62 第3次实验
  students/net1814080903320/activity_run.xml
  students/net1814080903320/run.jpg
Labels: Good, Pass3

#616 #3 #26 第三次实验
  students/net1814080903110/activity_net1814080903110.xml
  students/net1814080903110/ribcbackground.png
Labels: Good, Pass3

#618 #3 #66 第三次实验
  students/net1814080903106/src/main/res/drawable/transparentwords.png
  students/net1814080903106/src/main/res/layout/activity_game.xml
  students/net1814080903106/src/main/res/layout/activity_history_score.xml
  students/net1814080903106/src/main/res/layout/activity_main.xml
Labels: Good, Pass3

#619 #3 #445 第三次实验
  students/net1814080903123/novel_search.xml
  students/net1814080903123/tupian.jpg
Labels: Good, Pass3

#623 #3 #435 第三次实验
  students/net1814080903302/activity_net1814080903302.xml
  students/net1814080903302/luyinji.jpg
Labels: Good, Pass3

#624 #3 #27 第三次实验
  students/net1814080903107/Buy.java
  students/net1814080903107/Command.java
  students/net1814080903107/Net1814080903107Activity.java
  students/net1814080903107/Recommend.java
  students/net1814080903107/SearchActivity.java
  students/net1814080903107/StoreActivity.java
  students/net1814080903107/activity_recommend.xml
  students/net1814080903107/kfc.jpg
  students/net1814080903107/sqsm.jpg
Labels: Good, Pass3

#625 #3 #30 第三次实验
  students/net1814080903105/activity_main.xml
  students/net1814080903105/homepage.jpg
Labels: Good, Pass3

#627 #3 #29 第三次实验
  students/net1814080903124/activity_main.xml
  students/net1814080903124/background.jpg
Labels: Good, Pass3

#634 #3 #24 第三次实验
  students/net1814080903111/logo1.jpg
  students/net1814080903111/net_1814080903111_activity.xml
Labels: Good, Pass3

#635 #3 #23 第三次实验
  students/net1814080903102/app/src/main/res/drawable/logo.jpg
  students/net1814080903102/app/src/main/res/layout/activity_main.xml
Labels: Good, Pass3

#633 #3 #32 第三次实验
  students/net1814080903121/AddActivity.java
  students/net1814080903121/AndroidManifest.xml
  students/net1814080903121/EditActivity.java
  students/net1814080903121/Net1814080903121Activity.java
  students/net1814080903121/ShownameActivity.java
  students/net1814080903121/activity_main.xml
  students/net1814080903121/app/src/main/java/edu/hzuapps/androidlabs/net1814080903121/Net1814080903121Activity.java
  students/net1814080903121/head.jpg
  students/net1814080903121/tx.jpg
Labels: Good, Pass3

#631 #3 #31 第3次实验
  students/net1814080903119/activity_main.xml
  students/net1814080903119/tu1.jpg
  students/net1814080903119/tu2.jpg
  students/net1814080903119/tu3.jpg
  students/net1814080903119/tu4.jpg
Labels: Good, Pass3

#630 #3 #171 第三次实验
  students/net1814080903104/AndroidManifest.xml
  students/net1814080903104/GetReward.java
  students/net1814080903104/Net1814080903104Activity.java
  students/net1814080903104/SearchMess.java
  students/net1814080903104/activity_main.xml
  students/net1814080903104/res/drawable/backgroud.jpg
  students/net1814080903104/res/drawable/logo.jpg
  students/net1814080903104/res/drawable/main.jpg
  students/net1814080903104/res/layout/activity_get_reward.xml
  students/net1814080903104/res/layout/activity_main.xml
  students/net1814080903104/res/layout/activity_search_mess.xml
Labels: Good, Pass3

#642 #2 #202 第二次实验
  students/sec1814080911222/app/src/main/AndroidManifest.xml
  students/sec1814080911222/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911222/PerformanceActivity.java
  students/sec1814080911222/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911222/PlanActivity.java
  students/sec1814080911222/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911222/sec1814080911222Activity.java
Labels: Pass2

#650 #2 #382 第二次实验
  students/net1814080903130/AndroidManifest.xml
  students/net1814080903130/Chat.java
  students/net1814080903130/Net1814080903130Activity.java
Labels: Pass2

#649 #3 #142 第三次实验
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/DownloadActivity.java
  students/net1814080903117/app/src/main/java/edu/hzuapps/androidlabs/net1814080903117/UploadActivity.java
  students/net1814080903117/app/src/main/res/drawable/bg.jpg
  students/net1814080903117/app/src/main/res/drawable/download.jpg
  students/net1814080903117/app/src/main/res/drawable/upload.jpg
  students/net1814080903117/app/src/main/res/layout/activity_download.xml
  students/net1814080903117/app/src/main/res/layout/activity_net1814080903117.xml
  students/net1814080903117/app/src/main/res/layout/activity_upload.xml
Labels: Pass3

#655 #3 #134 实验3
  students/net1814080903129/src/main/res/drawable/js.png
  students/net1814080903129/src/main/res/layout/activity_main.xml
Labels: Pass3

#661 #3 #145 实验3
  students/net1814080903126/src/main/res/drawable/boom.jpg
  students/net1814080903126/src/main/res/layout/activity_net1814080903126.xml
Labels: Pass3

#664 #3 #122 第三次实验
  students/net1814080903116/src/main/activity_main.xml
  students/net1814080903116/src/main/main.jpg
Labels: Pass3

#684 #2 #333 第二次实验
  students/sec1814080911219/app/src/main/AndroidManifest.xml
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/CipheruploadActivity.java
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/Sec1814080911219Activity.java
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/ShowfilelistActivity.java
  students/sec1814080911219/app/src/main/res/layout/activity_cipherupload.xml
  students/sec1814080911219/app/src/main/res/layout/activity_main.xml
  students/sec1814080911219/app/src/main/res/layout/activity_showfilelist.xml
  students/sec1814080911219/app/src/main/res/values/colors.xml
  students/sec1814080911219/app/src/main/res/values/strings.xml
  students/sec1814080911219/app/src/main/res/values/styles.xml
Labels: Good, Pass2

#691 #3#54第三次实验
  students/net1814080903316/net_1814080903316_activity.xml
  students/net1814080903316/school.jpg
Labels: Pass3

#687 #3 #131 第三次实验
  students/net1814080903132/activity_main.xml
  students/net1814080903132/home_design.jpg
Labels: Pass3

#689 #3 #396 第三次实验
  students/net1814080903127/activity_main.xml
  students/net1814080903127/background.png
Labels: Pass3

#690 #3 #79 第三次实验
  students/net1814080903312/app/src/main/res/drawable-v24/wangyiyun_top.PNG
  students/net1814080903312/app/src/main/res/drawable/wangyiyun3.png
  students/net1814080903312/app/src/main/res/layout/activity_main.xml
  students/net1814080903312/app/src/main/res/layout/activity_music.xml
  students/net1814080903312/app/src/main/res/layout/activity_play.xml
Labels: Pass3

#693 #3 #595 第三次实验
  students/net1814080903120/ImageActivity.java
  students/net1814080903120/ImageotherActivity.java
  students/net1814080903120/image_act.xml
  students/net1814080903120/image_actother.xml
  students/net1814080903120/kkk.jpg
  students/net1814080903120/lll.jpg
Labels: Pass3

#694 #3 提交实验三代码
  students/net1814080903301/activity_main.xml
  students/net1814080903301/myimage.jpg
Labels: Pass3

#696 #2 #362 提交实验2
  students/sec1814080911108/app/src/main/AndroidManifest.xml
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/LoveListActivity.java
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/SearchActivity.java
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/Sec1814080911108Activity.java
  students/sec1814080911108/app/src/main/res/layout/activity_love_list.xml
  students/sec1814080911108/app/src/main/res/layout/activity_search.xml
  students/sec1814080911108/app/src/main/res/layout/activity_sec1814080911108.xml
  students/sec1814080911108/app/src/main/res/values/colors.xml
  students/sec1814080911108/app/src/main/res/values/strings.xml
  students/sec1814080911108/app/src/main/res/values/styles.xml
Labels: Pass2

#700 #2 #319 第2次实验
  students/sec1814080911131/First_Activity.java
  students/sec1814080911131/Four_Activity.java
  students/sec1814080911131/Sec1814080911131Activity.java
  students/sec1814080911131/Second_Activity.java
  students/sec1814080911131/SplashActicity.java
  students/sec1814080911131/Third_Activity.java
Labels: Pass2

#703 #3 #76 第三次实验
  students/net1814080903334/activity_main.xml
  students/net1814080903334/zhuye.png
Labels: Pass3

#704 #2 #57 第2次实验
  students/net1814080903305/AlarmSetActivity.java
  students/net1814080903305/AndroidManifest.xml
  students/net1814080903305/MainActivity.java
  students/net1814080903305/TimeDisplayActivity.java
  students/net1814080903305/activity_main.xml
  students/net1814080903305/time.jpg
Labels: Pass2, Pass3

#707 #3 #281 第三次试验
  students/net1814080903321/AndroidManifest.xml
  students/net1814080903321/Net1814080903321Activity.java
  students/net1814080903321/ShowActivity.java
  students/net1814080903321/StoreActivity.java
  students/net1814080903321/activity_store.xml
  students/net1814080903321/yihetang.jpg
Labels: Pass3

#705 #3 #267 第3次实验
  students/net1814080903329/activity_homework_manger.xml
  students/net1814080903329/activity_main.xml
  students/net1814080903329/activity_net1814080903329.xml
  students/net1814080903329/activity_picture.xml
  students/net1814080903329/zuoye.png
Labels: Pass3

#708 #3 #64 第三次实验
  students/net1814080903133/src/main/AndroidManifest.xml
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/Net1814080903133Activity.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/NovelReadActivity.java
  students/net1814080903133/src/main/java/edu/huzapps/androidlabs/SettingActivity.java
  students/net1814080903133/src/main/res/drawable/back_image.jpg
  students/net1814080903133/src/main/res/layout/activity_novel_read.xml
Labels: Pass3

#698 #2 #50 第2次实验
  students/sec1814080911106/EditActivity.java
  students/sec1814080911106/PictureActivity.java
  students/sec1814080911106/Sec1814080911106Activity.java
  students/sec1814080911106/activity_main.xml
Labels: Good, Pass2

#710 #3 #280 第三次实验
  students/net1814080903326/activity_main.xml
  students/net1814080903326/timg.jpg
Labels: Pass3

#713 #2 #170 第二次实验
  students/net1812070504101/main/AndroidManifest.xml
  students/net1812070504101/main/java/edu/hzuapp/androidlabs/net1812070504101/CheckActivity.java
  students/net1812070504101/main/java/edu/hzuapp/androidlabs/net1812070504101/Net1812070504101Activity.java
  students/net1812070504101/main/java/edu/hzuapp/androidlabs/net1812070504101/StatisticActivity.java
Labels: Good, Pass2

#714 #2 #255 第2次实验
  students/sec1814080911234/app/src/main/AndroidManifest.xml
  students/sec1814080911234/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911234/CreateActivity.java
  students/sec1814080911234/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911234/DateActivity.java
  students/sec1814080911234/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911234/FestivalActivity.java
  students/sec1814080911234/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911234/Sec1814080911234Activity.java
Labels: Good, Pass2

#712 #3 #20 第三次实验
  students/net1814080903140/activity_main.xml
  students/net1814080903140/drawable/bg.png
  students/net1814080903140/drawable/icon_add.png
  students/net1814080903140/drawable/icon_more.png
Labels: Pass3

#711 #3 #244 第3次实验
  students/net1814080903203/ManageActivity.java
  students/net1814080903203/Net1814080903203Activity.java
  students/net1814080903203/ViewActivity.java
  students/net1814080903203/logo.jpg
  students/net1814080903203/net_1814080903203_activity.xml
Labels: Pass3

#722 #3 #165 第3次实验
  students/net1814080903137/res/drawable/bg.jpeg
  students/net1814080903137/res/drawable/bt.JPG
  students/net1814080903137/res/drawable/loge.png
  students/net1814080903137/res/layout/activity_main.xml
Labels: Pass3

#726 #2 #282 第2次实验
  students/sec1814080911224/app/src/main/AndroidManifest.xml
  students/sec1814080911224/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911224/DrawActivity.java
  students/sec1814080911224/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911224/ShuffleActivity.java
  students/sec1814080911224/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911224/sec1814080911224Activity.java
Labels: Good, Pass2

#727 #2 #284 第2次实验
  students/sec1814080911208/app/src/main/AndroidManifest.xml
  students/sec1814080911208/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911208/SaveActivity.java
  students/sec1814080911208/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911208/ScoreActivity.java
  students/sec1814080911208/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911208/sec1814080911208Activity.java
Labels: Good, Pass2

#728 #2 #300 第2次实验
  students/sec1814080911207/app/src/main/AndroidManifest.xml
  students/sec1814080911207/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911207/RecordActivity.java
  students/sec1814080911207/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911207/RemindActivity.java
  students/sec1814080911207/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911207/sec1814080911207Activity.java
Labels: Good, Pass2

#729 #2 #302 第二次实验
  students/sec1814080911214/app/src/main/AndroidManifest.xml
  students/sec1814080911214/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911214/DepositActivity.java
  students/sec1814080911214/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911214/QueryActivity.java
  students/sec1814080911214/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911214/sec1814080911214Activity.java
Labels: Good, Pass2

#732 #3 #499 第三次实验
  students/net1814080903313/activity_img.xml
  students/net1814080903313/img1.jpg
Labels: Pass3

#702 #3 #305 第三次实验
  students/net1814080903308/AndroidManifest.xml
  students/net1814080903308/MainActivity.java
  students/net1814080903308/MusicActivity.java
  students/net1814080903308/Net1814080903308Activity.java
  students/net1814080903308/ShareActivity.java
  students/net1814080903308/activity_music.xml
  students/net1814080903308/activity_net1814080903308.xml
  students/net1814080903308/activity_share.xml
  students/net1814080903308/logo1.png
  students/net1814080903308/logo2.png
  students/net1814080903308/net1814080903308.png
Labels: Pass3

#748 #3 #59 第三次实验
  students/net1814080903303/backgroud.png
Labels: Pass3

#750 #2 #259 第2次实验
  students/net1814080903342/AndroidManifest.xml
  students/net1814080903342/Net1814080903342Activity.java
  students/net1814080903342/SearchIdActivity.java
  students/net1814080903342/SearchTradingActivity.java
Labels: Pass2

#736 #2 #323 提交第二次实验
  students/sec1814080911125/AndroidManifest.xml
  students/sec1814080911125/FailGameSceneActivity.java
  students/sec1814080911125/GameSceneActivity.java
  students/sec1814080911125/Sec1814080911125Activity.java
Labels: Pass2

#737 #2 #41 第二次实验
  students/sec1814080911205/AddCityActivity.java
  students/sec1814080911205/AddTextActivity.java
  students/sec1814080911205/AndroidManifest.xml
  students/sec1814080911205/CheckActivity.java
  students/sec1814080911205/Sec1814080911205Activity.java
Labels: Pass2

#740 #2 #42 第二次实验
  students/sec1814080911210/AndroidManifest.xml
  students/sec1814080911210/java/edu/hzuapps/androidlabs/sec1814080911210/AddinfoActivity.java
  students/sec1814080911210/java/edu/hzuapps/androidlabs/sec1814080911210/LocationActivity.java
  students/sec1814080911210/java/edu/hzuapps/androidlabs/sec1814080911210/Sec1814080911210Activity.java
Labels: Pass2

#741 #2 #283 第2次实验
  students/sec1814080911213/app/src/main/AndroidManifest.xml
  students/sec1814080911213/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911213/PerformanceActivity.java
  students/sec1814080911213/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911213/RankActivity.java
  students/sec1814080911213/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911213/Sec1814080911213Activity.java
Labels: Pass2

#749 #1 #2 #3 #294 第一次实验
  students/net1814080903324/AndroidManifest.xml
  students/net1814080903324/Net1814080903324.java
  students/net1814080903324/Net1814080903324Activity.java
  students/net1814080903324/UploadPictures.java
  students/net1814080903324/activity_main.xml
  students/net1814080903324/net1814080903324.png
  students/net1814080903324/picture_contorl.jpg
Labels: Pass1, Pass2, Pass3

#751 #4 #192 第四次实验
  students/net1814080903317/FoundItMainAdapter.java
  students/net1814080903317/Net1814080903317FoundItMainActivity.java
  students/net1814080903317/activity_foundit_main.xml
  students/net1814080903317/item__main_foundit_content.xml
  students/net1814080903317/实验四运行结果截图.jpg
Labels: Good, Pass4

#753 第三次实验
  students/net1814080903218/activity_ask_for_leave1814080903218.xml
  students/net1814080903218/activity_net1814080903218.xml
  students/net1814080903218/res/drawable/head.jpg
Labels: Pass3

#765 #3 #171 第三次实验
  students/net1812070504101/AndroidManifest.xml
  students/net1812070504101/java/edu/hzuapp/androidlabs/net1812070504101/CheckActivity.java
  students/net1812070504101/java/edu/hzuapp/androidlabs/net1812070504101/Net1812070504101Activity.java
  students/net1812070504101/java/edu/hzuapp/androidlabs/net1812070504101/StatisticActivity.java
  students/net1812070504101/res/activity_main.xml
  students/net1812070504101/res/mipmap-xxhdpi/bg.jpg
Labels: Pass3

#763 #2 #3 #82 第2、3次实验
  students/net1814080903224/CareActivity.java
  students/net1814080903224/Net1814080903224Activity.java
  students/net1814080903224/ProductionActivity.java
  students/net1814080903224/RecommendActivity.java
  students/net1814080903224/activity_main.xml
  students/net1814080903224/use1.jpg
Labels: Pass3

#762 #3 #85 第3次实验
  students/net1814080903231/res/drawable/timg.jpg
  students/net1814080903231/res/layout/activity_main.xml
Labels: Pass3

#769 #3 #202 第3次实验
  students/sec1814080911222/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911222/PerformanceActivity.java
  students/sec1814080911222/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911222/PlanActivity.java
  students/sec1814080911222/app/src/main/res/drawable/bg.jpg
  students/sec1814080911222/app/src/main/res/drawable/performance.jpg
  students/sec1814080911222/app/src/main/res/drawable/plan.jpg
  students/sec1814080911222/app/src/main/res/layout/activity_performance.xml
  students/sec1814080911222/app/src/main/res/layout/activity_plan.xml
  students/sec1814080911222/app/src/main/res/layout/sec_1814080911222_activity.xml
Labels: Pass3

#777 #3 #364 第3次实验
  students/net1814080903236/.idea/render.experimental.xml
  students/net1814080903236/app/src/main/AndroidManifest.xml
  students/net1814080903236/app/src/main/java/edu/hzuapps/androidlabs/net1814080903236/MainActivity.java
  students/net1814080903236/app/src/main/java/edu/hzuapps/androidlabs/net1814080903236/Net1814080903236Activity.java
  students/net1814080903236/app/src/main/java/edu/hzuapps/androidlabs/net1814080903236/RecordActivity.java
  students/net1814080903236/app/src/main/java/edu/hzuapps/androidlabs/net1814080903236/RemindActivity.java
  students/net1814080903236/app/src/main/res/drawable/main.jpg
  students/net1814080903236/app/src/main/res/drawable/remind.jpg
  students/net1814080903236/app/src/main/res/layout/activity_main.xml
  students/net1814080903236/app/src/main/res/layout/activity_record.xml
  students/net1814080903236/app/src/main/res/layout/activity_remind.xml
Labels: Pass2, Pass3

#781 #3 #37 第三次实验
  students/sec1814080911113/activity_main.xml
  students/sec1814080911113/qqmusic.jpg
Labels: Good, Pass3

#783 #3 #39 第3次实验
  students/sec1814080911102/app/src/main/res/drawable/homepage_clock.jpg
  students/sec1814080911102/app/src/main/res/layout/activity_main.xml
Labels: Good, Pass3

#784 #3 #50 第3次实验
  students/sec1814080911106/activity_main.xml
  students/sec1814080911106/background.jpg
Labels: Good, Pass3

#786 #3 #42 第三次实验
  students/sec1814080911210/activity_sec1814080911210.xml
  students/sec1814080911210/map.png
Labels: Good, Pass3

#787 #3 #329 提交第三次实验+修改第二次实验
  students/sec1814080911130/app/src/main/java/edu/hzuapps/androidlabs/Sec1814080911130Activity.java
  students/sec1814080911130/app/src/main/res/drawable/background.jpg
  students/sec1814080911130/app/src/main/res/layout/activity_sec1814080911130.xml
Labels: Good, Pass3
