Repository hzuapps/android-labs-2020, pull requests merged in 2021-01, with the labels that each got.

#1504 #5 #281 第5次实验和实验五报告
  students/net1814080903321/5.jpg
  students/net1814080903321/5_1.jpg
  students/net1814080903321/PersonalDetailsActivity.java
  students/net1814080903321/ShowActivity.java
  students/net1814080903321/activity_personal_details.xml
  students/net1814080903321/lab5.md
Labels: Pass5

#1507 #6 #362 提交实验6
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/SearchActivity.java
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/Sec1814080911108Activity.java
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/bookmarks/Bookmark.java
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/bookmarks/BookmarksActivity.java
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/helper/FileHelper.java
  students/sec1814080911108/app/src/main/java/edu/hzuapps/browers/webview/MyWebViewActivity.java
  students/sec1814080911108/app/src/main/res/drawable/bookmark_collect.png
  students/sec1814080911108/app/src/main/res/drawable/internet.png
  students/sec1814080911108/app/src/main/res/drawable/love_list.png
  students/sec1814080911108/app/src/main/res/drawable/refresh.png
  students/sec1814080911108/app/src/main/res/drawable/serch.png
  students/sec1814080911108/app/src/main/res/layout/activity_my_web_view.xml
  students/sec1814080911108/app/src/main/res/layout/activity_sec1814080911108.xml
  students/sec1814080911108/app/src/main/res/layout/activity_test.xml
  students/sec1814080911108/app/src/main/res/layout/xxx.xml
  students/sec1814080911108/app/src/main/res/values/strings.xml
  students/sec1814080911108/app/src/main/res/values/styles.xml
Labels: Pass6

#1508 #6 #81 第6次实验
  students/net1814080903220/AndroidManifest.xml
  students/net1814080903220/Net1814080903220EditActivity.java
  students/net1814080903220/activity_edit.xml
Labels: Pass6

#1509 #7 #50 第7次实验
  students/sec1814080911106/PhotoActivity.java
  students/sec1814080911106/activity_photo.xml
Labels: Pass7

#1515 #5 #315 第5次实验
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/LookPyqActivity.java
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/SendPyqActivity.java
  students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/filehelper/FileHelper.java
Labels: Pass5

#1519 #7 #52 第七次实验
  students/net1814080903304/activity_test.xml
  students/net1814080903304/lab4.jpg
  students/net1814080903304/lab4.md
Labels: Pass7

#1520 #5 #43 #第5次实验
  students/sec1814080911230/java/RankActivity.java
  students/sec1814080911230/java/Sec1814080911230Activity.java
  students/sec1814080911230/java/StartGameActivity.java
  students/sec1814080911230/lab4.md
  students/sec1814080911230/lab4.png
  students/sec1814080911230/res/activity_main.xml
  students/sec1814080911230/res/activity_rank.xml
  students/sec1814080911230/res/activity_start_game.xml
  students/sec1814080911230/res/start_game_backgroud.jpg
Labels: Good, Pass5

#1523 #6 #62 第6次实验
  students/net1814080903320/RunActivity.java
  students/net1814080903320/shiyan6.PNG
Labels: Pass6

#1538 #6 #333 第六次实验+实验五、实验六报告及截图
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/CipheruploadActivity.java
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/Filepath.java
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/Sec1814080911219Activity.java
  students/sec1814080911219/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911219/ShowfilelistActivity.java
  students/sec1814080911219/app/src/main/res/layout/activity_cipherupload.xml
  students/sec1814080911219/app/src/main/res/layout/activity_main.xml
  students/sec1814080911219/app/src/main/res/layout/activity_showfilelist.xml
  students/sec1814080911219/lab3-4.PNG
  students/sec1814080911219/lab5-1.PNG
  students/sec1814080911219/lab5-2.PNG
  students/sec1814080911219/lab5-3.PNG
  students/sec1814080911219/lab5.md
  students/sec1814080911219/lab6-1.jpg
  students/sec1814080911219/lab6-2.jpg
  students/sec1814080911219/lab6-3.jpg
  students/sec1814080911219/lab6.md
Labels: Good, Pass6

#1539 #7 #42 第七次实验
  students/sec1814080911210/PhotoActivity.java
  students/sec1814080911210/activity_photo.xml
  students/sec1814080911210/lab7.PNG
Labels: Pass7

#1550 #6 #43 第6次实验
  students/sec1814080911230/java/FileDownloadActivity.java
  students/sec1814080911230/java/FileDownloader.java
  students/sec1814080911230/java/HttpClientActivity.java
  students/sec1814080911230/java/HttpClientUIActivity.java
  students/sec1814080911230/lab5(1).png
  students/sec1814080911230/lab5(2).png
  students/sec1814080911230/lab5.md
  students/sec1814080911230/lab6.md
  students/sec1814080911230/lab6.png
  students/sec1814080911230/lab7(1).png
  students/sec1814080911230/lab7(2).png
  students/sec1814080911230/lab7.md
  students/sec1814080911230/res/activity_file_download.xml
  students/sec1814080911230/res/activity_http_client.xml
Labels: Pass6

#1556 实验六
  students/sec1814080911243/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911243/FindActivity.java
  students/sec1814080911243/app/src/main/res/drawable/6.png
  students/sec1814080911243/exam/实验四.md
Labels: Pass6

#1559 实验报告六
  students/net1814080903220/Net1814080903220MainActivity.java
  students/net1814080903220/Net1814080903220RecordActivity.java
  students/net1814080903220/activity_record.xml
  students/net1814080903220/lab6.md
  students/net1814080903220/lab6result.png
Labels: Pass7

#1560 #5 #405 第五次实验报告
  students/sec1814080911138/10.png
  students/sec1814080911138/8.png
  students/sec1814080911138/9.png
  students/sec1814080911138/HttpClientActivity.java
  students/sec1814080911138/activity_http_client.xml
  students/sec1814080911138/lab5.md
Labels: Pass6

#1561 #7 #34 第7次实验
  students/sec1814080911202/AndroidManifest.xml
  students/sec1814080911202/BorrowActivity.java
  students/sec1814080911202/ManageActivity.java
  students/sec1814080911202/PhotoActivity.java
  students/sec1814080911202/activity_photo.xml
  students/sec1814080911202/lab7.md
  students/sec1814080911202/lab7.png
Labels: Pass7

#1624 #5 #294 第五次实验
  students/net1814080903324/Edit.java
  students/net1814080903324/activity_edit.xml
  students/net1814080903324/test4.java
Labels: Pass4, Pass5

#1631 #5 #292 第5次实验
  students/net1814080903332/Save.java
  students/net1814080903332/lab5.md
Labels: Pass5

#1632 #5 #435 第五次实验+实验报告五
  students/net1814080903302/Lab5.java
  students/net1814080903302/Net1814080903302Activity.java
  students/net1814080903302/activity_net1814080903302.xml
  students/net1814080903302/lab5.jpg
  students/net1814080903302/lab5.md
  students/net1814080903302/lab5_activity.xml
Labels: Pass5

#1683 #6 #382 实验六报告+剩余功能实现
  students/net1814080903130/AndroidManifest.xml
  students/net1814080903130/Chat.java
  students/net1814080903130/Lianxiren.java
  students/net1814080903130/Net1814080903130Activity.java
  students/net1814080903130/Qm.java
  students/net1814080903130/Resoubang.java
  students/net1814080903130/Web.java
  students/net1814080903130/Xiaoxi.java
  students/net1814080903130/activity_main.xml
  students/net1814080903130/chat.xml
  students/net1814080903130/content_main.xml
  students/net1814080903130/fragment_lianxiren.xml
  students/net1814080903130/fragment_resoubang.xml
  students/net1814080903130/fragment_xiaoxi.xml
  students/net1814080903130/lab6.md
  students/net1814080903130/nav_header_main.xml
  students/net1814080903130/qm.xml
  students/net1814080903130/qm_bar.xml
  students/net1814080903130/sy6.1.PNG
  students/net1814080903130/sy6.2.jpg
  students/net1814080903130/sy6.3.jpg
  students/net1814080903130/sy6.4.jpg
  students/net1814080903130/sy7.1.jpg
  students/net1814080903130/sy7.2.jpg
  students/net1814080903130/sy7.3.jpg
  students/net1814080903130/sy7.4.jpg
  students/net1814080903130/sy7.5.jpg
  students/net1814080903130/web.xml
Labels: Good, Pass6

#1700 #7 #79 没用到设备编程，完善实验
  students/net1814080903312/app/src/main/java/edu/hzuapps/androidlabs/net1814080903312/Net1814080903312Activity.java
  students/net1814080903312/app/src/main/res/layout/content.xml
Labels: Pass7
